# Generated by Django 5.2.17 on 2026-09-05 21:19

import apps.accounts.models
import apps.core.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('display_name', models.CharField(blank=True, help_text="Nom affiche dans l'interface (pseudonyme possible).", max_length=80)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Administrateur systeme'), ('NATIONAL_COORDINATOR', 'Coordinateur national'), ('CSIRT_ANALYST', 'Analyste CSIRT'), ('TRIAGER', 'Agent de triage'), ('DSI_ADMIN', 'Administrateur DSI'), ('ORGANIZATION_MANAGER', "Responsable d'organisation"), ('SECURITY_RESEARCHER', 'Chercheur en securite'), ('BUG_BOUNTY_RESEARCHER', 'Chercheur Bug Bounty'), ('AUDITOR', 'Auditeur'), ('PUBLIC_USER', 'Utilisateur public')], db_index=True, default='PUBLIC_USER', help_text="Role RBAC. Jamais modifiable par l'utilisateur lui-meme.", max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('pgp_public_key', models.TextField(blank=True)),
                ('pgp_fingerprint', models.CharField(blank=True, max_length=64)),
                ('mfa_enabled', models.BooleanField(default=False, help_text='Architecture prete ; activation par etape ulterieure.')),
                ('mfa_secret', models.CharField(blank=True, editable=False, max_length=64)),
                ('last_login_ip', models.CharField(blank=True, max_length=45)),
                ('accepted_policy_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'db_table': 'users',
                'ordering': ['email'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=120)),
                ('prefix', models.CharField(db_index=True, max_length=12)),
                ('key_hash', models.CharField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('EMAIL_VERIFICATION', "Verification d'email"), ('PASSWORD_RESET', 'Reinitialisation de mot de passe')], max_length=32)),
                ('token', models.CharField(default=apps.core.utils.random_token, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_tokens',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purpose', 'expires_at'], name='user_tokens_purpose_85d6ed_idx')],
            },
        ),
    ]
