# Generated by Django 5.2.17 on 2026-09-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_reminded_on',
            field=models.DateField(blank=True, help_text="Jour de la derniere relance de verification, pour n'en envoyer qu'une par jalon.", null=True),
        ),
    ]
