# Generated by Django 5.2.17 on 2026-09-11 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pgp_fingerprint',
        ),
        migrations.RemoveField(
            model_name='user',
            name='pgp_public_key',
        ),
    ]
