# Generated by Django 5.2.17 on 2026-09-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_user_pgp_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Nom affiché dans l'interface (pseudonyme possible).",
                max_length=80,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mfa_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Architecture prête ; activation par étape ultérieure.",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Administrateur système"),
                    ("NATIONAL_COORDINATOR", "Coordinateur national"),
                    ("CSIRT_ANALYST", "Analyste CSIRT"),
                    ("TRIAGER", "Agent de triage"),
                    ("DSI_ADMIN", "Administrateur DSI"),
                    ("ORGANIZATION_MANAGER", "Responsable d'organisation"),
                    ("SECURITY_RESEARCHER", "Chercheur en sécurité"),
                    ("BUG_BOUNTY_RESEARCHER", "Chercheur Bug Bounty"),
                    ("AUDITOR", "Auditeur"),
                    ("PUBLIC_USER", "Utilisateur public"),
                ],
                db_index=True,
                default="PUBLIC_USER",
                help_text="Rôle RBAC. Jamais modifiable par l'utilisateur lui-même.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("EMAIL_VERIFICATION", "Vérification d'email"),
                    ("PASSWORD_RESET", "Réinitialisation de mot de passe"),
                ],
                max_length=32,
            ),
        ),
    ]
