# Generated by Django 5.2.17 on 2026-09-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_verification_reminded_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mfa_confirmed_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_last_step",
            field=models.BigIntegerField(
                blank=True,
                editable=False,
                help_text="Dernier pas de temps TOTP consomme, pour refuser le rejeu.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mfa_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enrolement TOTP effectue. L'exigence, elle, decoule du role : voir apps.accounts.mfa.is_required.",
            ),
        ),
    ]
