# Generated by Django 5.2.17 on 2026-09-11 12:04

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_mfa_totp"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessAccount",
            fields=[],
            options={
                "verbose_name": "Compte metier",
                "verbose_name_plural": "Comptes metiers et administrateurs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.user",),
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ReporterAccount",
            fields=[],
            options={
                "verbose_name": "Compte signaleur",
                "verbose_name_plural": "Comptes signaleurs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.user",),
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
    ]
