# Generated by Django 5.2.17 on 2026-09-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_deux_listes_de_comptes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="accepted_policy_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Politique acceptee le"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Nom affiche dans l'interface (pseudonyme possible).",
                max_length=80,
                verbose_name="Nom affiche",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, unique=True, verbose_name="Adresse email"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="Adresse verifiee"),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Nom complet"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Compte actif"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Acces a l'administration"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login_ip",
            field=models.CharField(
                blank=True, max_length=45, verbose_name="Derniere IP de connexion"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mfa_confirmed_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Enregistre le"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mfa_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enrolement TOTP effectue. L'exigence, elle, decoule du role : voir apps.accounts.mfa.is_required.",
                verbose_name="Authentificateur enregistre",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="pgp_fingerprint",
            field=models.CharField(blank=True, max_length=64, verbose_name="Empreinte PGP"),
        ),
        migrations.AlterField(
            model_name="user",
            name="pgp_public_key",
            field=models.TextField(blank=True, verbose_name="Cle publique PGP"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=32, verbose_name="Telephone"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Administrateur systeme"),
                    ("NATIONAL_COORDINATOR", "Coordinateur national"),
                    ("CSIRT_ANALYST", "Analyste CSIRT"),
                    ("TRIAGER", "Agent de triage"),
                    ("DSI_ADMIN", "Administrateur DSI"),
                    ("ORGANIZATION_MANAGER", "Responsable d'organisation"),
                    ("SECURITY_RESEARCHER", "Chercheur en securite"),
                    ("BUG_BOUNTY_RESEARCHER", "Chercheur Bug Bounty"),
                    ("AUDITOR", "Auditeur"),
                    ("PUBLIC_USER", "Utilisateur public"),
                ],
                db_index=True,
                default="PUBLIC_USER",
                help_text="Role RBAC. Jamais modifiable par l'utilisateur lui-meme.",
                max_length=32,
                verbose_name="Role",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="verification_reminded_on",
            field=models.DateField(
                blank=True,
                help_text="Jour de la derniere relance de verification, pour n'en envoyer qu'une par jalon.",
                null=True,
                verbose_name="Derniere relance de verification",
            ),
        ),
    ]
