# Generated by Django 5.2.17 on 2026-09-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_libelles_francais"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="accepted_policy_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Politique acceptée le"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Nom affiché dans l'interface (pseudonyme possible).",
                max_length=80,
                verbose_name="Nom affiché",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="Adresse vérifiée"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, verbose_name="Accès à l'administration"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_login_ip",
            field=models.CharField(
                blank=True, max_length=45, verbose_name="Dernière IP de connexion"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mfa_confirmed_at",
            field=models.DateTimeField(
                blank=True, editable=False, null=True, verbose_name="Enregistré le"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mfa_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enrôlement TOTP effectué. L'exigence, elle, découle du rôle : voir apps.accounts.mfa.is_required.",
                verbose_name="Authentificateur enregistré",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mfa_last_step",
            field=models.BigIntegerField(
                blank=True,
                editable=False,
                help_text="Dernier pas de temps TOTP consommé, pour refuser le rejeu.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="pgp_public_key",
            field=models.TextField(blank=True, verbose_name="Clé publique PGP"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=32, verbose_name="Téléphone"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Administrateur système"),
                    ("NATIONAL_COORDINATOR", "Coordinateur national"),
                    ("CSIRT_ANALYST", "Analyste CSIRT"),
                    ("TRIAGER", "Agent de triage"),
                    ("DSI_ADMIN", "Administrateur DSI"),
                    ("ORGANIZATION_MANAGER", "Responsable d'organisation"),
                    ("SECURITY_RESEARCHER", "Chercheur en sécurité"),
                    ("BUG_BOUNTY_RESEARCHER", "Chercheur Bug Bounty"),
                    ("AUDITOR", "Auditeur"),
                    ("PUBLIC_USER", "Utilisateur public"),
                ],
                db_index=True,
                default="PUBLIC_USER",
                help_text="Rôle RBAC. Jamais modifiable par l'utilisateur lui-même.",
                max_length=32,
                verbose_name="Rôle",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="verification_reminded_on",
            field=models.DateField(
                blank=True,
                help_text="Jour de la dernière relance de vérification, pour n'en envoyer qu'une par jalon.",
                null=True,
                verbose_name="Dernière relance de vérification",
            ),
        ),
        migrations.AlterField(
            model_name="usertoken",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("EMAIL_VERIFICATION", "Vérification d'email"),
                    ("PASSWORD_RESET", "Réinitialisation de mot de passe"),
                ],
                max_length=32,
            ),
        ),
    ]
