# Generated by Django 5.2.17 on 2026-09-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_accepted_policy_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="pgp_fingerprint",
        ),
        migrations.RemoveField(
            model_name="user",
            name="pgp_public_key",
        ),
    ]
