# Generated by Django 5.2.17 on 2026-09-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_user_pgp_fingerprint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_senior_analyst",
            field=models.BooleanField(
                default=False,
                help_text="Accorde à un analyste CSIRT la validation des qualifications (étape 4), jamais la sienne.",
                verbose_name="Analyste senior",
            ),
        ),
    ]
