# Generated by Django 5.2.17 on 2026-09-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_remove_user_pgp_fingerprint_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_senior_analyst",
            field=models.BooleanField(
                default=False,
                help_text="Permission individuelle : un analyste CSIRT senior peut valider la qualification d'un autre analyste (étape 4). Sans effet sur les autres rôles.",
                verbose_name="Analyste senior",
            ),
        ),
    ]
