# Generated by Django 5.2.17 on 2026-09-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_senior_analyst"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_senior_analyst",
            field=models.BooleanField(
                default=False,
                help_text="À cocher avec le rôle « Analyste CSIRT » : l'analyste senior peut valider la qualification d'un autre analyste (étape 4, 4 yeux). Réservé au rôle Analyste CSIRT.",
                verbose_name="Analyste senior",
            ),
        ),
    ]
