# Generated by Django 5.2.17 on 2026-10-01 01:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_codes_de_secours_mfa"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="businessaccount",
            options={
                "verbose_name": "Compte métier",
                "verbose_name_plural": "Comptes métiers et administrateurs",
            },
        ),
    ]
