# Generated by Django 5.2.17 on 2026-10-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_libelles_accentues"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pending_activation",
            field=models.BooleanField(
                default=False, verbose_name="Activation par email en attente"
            ),
        ),
    ]
