# Generated by Django 5.2.17 on 2026-09-05 21:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
            ],
            options={
                'verbose_name': "Reference d'advisory",
                'verbose_name_plural': "References d'advisory",
                'db_table': 'advisory_references',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AdvisoryTimelineEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('happened_on', models.DateField()),
                ('label', models.CharField(max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Etape de chronologie',
                'verbose_name_plural': 'Chronologie publique',
                'db_table': 'advisory_timeline_entries',
                'ordering': ['happened_on', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisory_id', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('title', models.CharField(max_length=250)),
                ('summary', models.TextField(help_text='Resume public. Markdown autorise.')),
                ('product', models.CharField(blank=True, max_length=200)),
                ('affected_versions', models.CharField(blank=True, max_length=255)),
                ('fixed_versions', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, help_text='Markdown autorise.')),
                ('impact', models.TextField(blank=True, help_text='Markdown autorise.')),
                ('solution', models.TextField(blank=True, help_text='Markdown autorise.')),
                ('workaround', models.TextField(blank=True, help_text='Markdown autorise.')),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critique'), ('HIGH', 'Elevee'), ('MEDIUM', 'Moyenne'), ('LOW', 'Faible'), ('INFO', 'Informative')], db_index=True, default='MEDIUM', max_length=16)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('cvss_vector', models.CharField(blank=True, max_length=120)),
                ('credit', models.CharField(blank=True, help_text='Credit affiche publiquement, conforme au choix du chercheur.', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('IN_REVIEW', 'En relecture'), ('APPROVED', 'Approuve'), ('SCHEDULED', 'Planifie'), ('PUBLISHED', 'Publie'), ('RETRACTED', 'Retire')], db_index=True, default='DRAFT', max_length=16)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('retracted_reason', models.TextField(blank=True)),
                ('case', models.ForeignKey(blank=True, help_text='Case prive source. Jamais expose publiquement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisories', to='coordination.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_advisories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advisory',
                'verbose_name_plural': 'Advisories',
                'db_table': 'advisories',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
