# Generated by Django 5.2.17 on 2026-09-05 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disclosures', '0001_initial'),
        ('organizations', '0001_initial'),
        ('vulnerabilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory',
            name='cve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisories', to='vulnerabilities.cve'),
        ),
        migrations.AddField(
            model_name='advisory',
            name='cwe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisories', to='vulnerabilities.cwe'),
        ),
        migrations.AddField(
            model_name='advisory',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisories', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='advisory',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_advisories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advisoryreference',
            name='advisory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_references', to='disclosures.advisory'),
        ),
        migrations.AddField(
            model_name='advisorytimelineentry',
            name='advisory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='disclosures.advisory'),
        ),
        migrations.AddIndex(
            model_name='advisory',
            index=models.Index(fields=['status', '-published_at'], name='advisories_status_d08b44_idx'),
        ),
    ]
