# Generated by Django 5.2.17 on 2026-09-13 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coordination", "0005_alter_case_scope_alter_case_severity_and_more"),
        ("disclosures", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisory",
            name="case",
            field=models.ForeignKey(
                blank=True,
                help_text="Case privé source. Jamais exposé publiquement.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="advisories",
                to="coordination.case",
            ),
        ),
        migrations.AlterField(
            model_name="advisory",
            name="credit",
            field=models.CharField(
                blank=True,
                help_text="Crédit affiché publiquement, conforme au choix du chercheur.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="advisory",
            name="description",
            field=models.TextField(blank=True, help_text="Markdown autorisé."),
        ),
        migrations.AlterField(
            model_name="advisory",
            name="impact",
            field=models.TextField(blank=True, help_text="Markdown autorisé."),
        ),
        migrations.AlterField(
            model_name="advisory",
            name="severity",
            field=models.CharField(
                choices=[
                    ("CRITICAL", "Critique"),
                    ("HIGH", "Élevée"),
                    ("MEDIUM", "Moyenne"),
                    ("LOW", "Faible"),
                    ("INFO", "Informative"),
                ],
                db_index=True,
                default="MEDIUM",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="advisory",
            name="solution",
            field=models.TextField(blank=True, help_text="Markdown autorisé."),
        ),
        migrations.AlterField(
            model_name="advisory",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("IN_REVIEW", "En relecture"),
                    ("APPROVED", "Approuvé"),
                    ("SCHEDULED", "Planifié"),
                    ("PUBLISHED", "Publié"),
                    ("RETRACTED", "Retiré"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="advisory",
            name="summary",
            field=models.TextField(help_text="Résumé public. Markdown autorisé."),
        ),
        migrations.AlterField(
            model_name="advisory",
            name="workaround",
            field=models.TextField(blank=True, help_text="Markdown autorisé."),
        ),
    ]
