# Generated by Django 5.2.17 on 2026-09-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("disclosures", "0003_alter_advisory_case_alter_advisory_credit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advisory",
            name="cvss_vector",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
