# Generated by Django 5.2.17 on 2026-10-01 01:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("disclosures", "0004_alter_advisory_cvss_vector"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="advisoryreference",
            options={
                "ordering": ["title"],
                "verbose_name": "Référence d'advisory",
                "verbose_name_plural": "Références d'advisory",
            },
        ),
        migrations.AlterModelOptions(
            name="advisorytimelineentry",
            options={
                "ordering": ["happened_on", "position"],
                "verbose_name": "Étape de chronologie",
                "verbose_name_plural": "Chronologie publique",
            },
        ),
    ]
