# Generated by Django 5.2.17 on 2026-09-05 21:19

import apps.attachments.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_name', models.CharField(editable=False, max_length=80, unique=True)),
                ('file', models.FileField(max_length=300, upload_to=apps.attachments.models.attachment_upload_path)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('scan_status', models.CharField(choices=[('PENDING', 'Analyse en attente'), ('CLEAN', 'Sain'), ('INFECTED', 'Infecte'), ('SKIPPED', 'Analyse non disponible'), ('ERROR', "Erreur d'analyse")], default='PENDING', max_length=16)),
                ('scan_detail', models.CharField(blank=True, max_length=255)),
                ('is_pgp_encrypted', models.BooleanField(default=False)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('download_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Piece jointe',
                'verbose_name_plural': 'Pieces jointes',
                'db_table': 'attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
