# Generated by Django 5.2.17 on 2026-09-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="scan_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Analyse en attente"),
                    ("CLEAN", "Sain"),
                    ("INFECTED", "Infecté"),
                    ("SKIPPED", "Analyse non disponible"),
                    ("ERROR", "Erreur d'analyse"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
