# Generated by Django 5.2.17 on 2026-10-01 01:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attachments", "0004_alter_attachment_scan_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attachment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Pièce jointe",
                "verbose_name_plural": "Pièces jointes",
            },
        ),
    ]
