# Generated by Django 5.2.17 on 2026-09-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=120, unique=True)),
                ('label', models.CharField(max_length=200)),
                ('value', models.TextField(blank=True, help_text='Contenu Markdown autorise.')),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Parametre de site',
                'verbose_name_plural': 'Parametres de site',
                'db_table': 'site_settings',
                'ordering': ['key'],
            },
        ),
    ]
