# Generated by Django 5.2.17 on 2026-09-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SequenceCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("last_value", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "core_sequence_counters",
            },
        ),
    ]
