# Generated by Django 5.2.17 on 2026-09-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesetting",
            name="value",
            field=models.TextField(blank=True, help_text="Contenu Markdown autorisé."),
        ),
    ]
