# Generated by Django 5.2.17 on 2026-09-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_sequencecounter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesetting",
            options={
                "ordering": ["key"],
                "verbose_name": "Paramètre de site",
                "verbose_name_plural": "Paramètres de site",
            },
        ),
        migrations.AlterField(
            model_name="sitesetting",
            name="value",
            field=models.TextField(blank=True, help_text="Contenu Markdown autorisé."),
        ),
    ]
