# Generated by Django 5.2.17 on 2026-10-01 01:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_sequencecounter"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesetting",
            options={
                "ordering": ["key"],
                "verbose_name": "Paramètre de site",
                "verbose_name_plural": "Paramètres de site",
            },
        ),
    ]
