# Generated by Django 5.2.17 on 2026-10-01 03:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_libelles_accentues"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NationalPGPKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_key", models.TextField(verbose_name="Clé publique armurée")),
                ("fingerprint", models.CharField(max_length=64, verbose_name="Empreinte")),
                ("key_created_at", models.DateTimeField(verbose_name="Créée le")),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Expire le"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "published_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Publiée par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clé PGP nationale",
                "verbose_name_plural": "Clés PGP nationales",
                "db_table": "national_pgp_keys",
                "ordering": ["-created_at"],
            },
        ),
    ]
