# Generated by Django 5.2.17 on 2026-10-01 23:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_cle_pgp_nationale"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PGPKeyDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fingerprint", models.CharField(max_length=64, verbose_name="Empreinte")),
                ("payload", models.TextField(blank=True, verbose_name="Clé privée chiffrée")),
                ("expires_at", models.DateTimeField(verbose_name="Expire le")),
                (
                    "fetch_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="Récupérations"),
                ),
                (
                    "retrieved_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Récupérée le"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Annulée le"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Préparée par",
                    ),
                ),
                (
                    "national_key",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="core.nationalpgpkey",
                        verbose_name="Clé nationale",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pgp_key_deliveries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinataire",
                    ),
                ),
            ],
            options={
                "verbose_name": "Remise de clé PGP",
                "verbose_name_plural": "Remises de clé PGP",
                "db_table": "pgp_key_deliveries",
                "ordering": ["-created_at"],
            },
        ),
    ]
