# Generated by Django 5.2.17 on 2026-09-05 21:19

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordination', '0001_initial'),
        ('disclosures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVE',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cve_id', models.CharField(max_length=24, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^CVE-\\d{4}-\\d{4,10}$', 'Format attendu: CVE-2026-1234')])),
                ('state', models.CharField(choices=[('REQUESTED', 'Demande'), ('RESERVED', 'Reserve'), ('PUBLISHED', 'Publie'), ('REJECTED', 'Rejete')], default='RESERVED', max_length=16)),
                ('summary', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('cvss_vector', models.CharField(blank=True, max_length=120)),
                ('url', models.URLField(blank=True)),
                ('in_cisa_kev', models.BooleanField(default=False)),
                ('epss_score', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CVE',
                'verbose_name_plural': 'CVE',
                'db_table': 'cves',
                'ordering': ['-cve_id'],
            },
        ),
        migrations.CreateModel(
            name='CWE',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^CWE-\\d+$', 'Format attendu: CWE-79')])),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'CWE',
                'verbose_name_plural': 'CWE',
                'db_table': 'cwes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='VulnerabilityReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('kind', models.CharField(choices=[('ADVISORY', 'Advisory'), ('PATCH', 'Correctif'), ('EXPLOIT', 'Exploit'), ('ARTICLE', 'Article'), ('VENDOR', 'Editeur'), ('OTHER', 'Autre')], default='OTHER', max_length=16)),
                ('is_public', models.BooleanField(default=False, help_text='Une reference publique peut apparaitre dans un advisory.')),
                ('advisory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='disclosures.advisory')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', to='coordination.case')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
                'db_table': 'vulnerability_references',
                'ordering': ['kind', 'title'],
            },
        ),
    ]
