# Generated by Django 5.2.17 on 2026-09-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerabilities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cve",
            name="state",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Demandé"),
                    ("RESERVED", "Réservé"),
                    ("PUBLISHED", "Publié"),
                    ("REJECTED", "Rejeté"),
                ],
                default="RESERVED",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityreference",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="Une référence publique peut apparaître dans un advisory.",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityreference",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ADVISORY", "Advisory"),
                    ("PATCH", "Correctif"),
                    ("EXPLOIT", "Exploit"),
                    ("ARTICLE", "Article"),
                    ("VENDOR", "Éditeur"),
                    ("OTHER", "Autre"),
                ],
                default="OTHER",
                max_length=16,
            ),
        ),
    ]
