# Generated by Django 5.2.17 on 2026-10-01 01:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vulnerabilities", "0002_alter_cve_state_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vulnerabilityreference",
            options={
                "ordering": ["kind", "title"],
                "verbose_name": "Référence",
                "verbose_name_plural": "Références",
            },
        ),
    ]
