# Generated by Django 5.2.17 on 2026-09-05 21:19

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordination', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('program_type', models.CharField(choices=[('VDP', 'Programme de divulgation (VDP)'), ('BUG_BOUNTY', 'Programme Bug Bounty')], db_index=True, default='VDP', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('ACTIVE', 'Actif'), ('PAUSED', 'Suspendu'), ('CLOSED', 'Cloture')], db_index=True, default='DRAFT', max_length=16)),
                ('confidentiality', models.CharField(choices=[('PUBLIC', 'Public'), ('RESTRICTED', 'Restreint'), ('PRIVATE', 'Prive (sur invitation)')], default='PUBLIC', max_length=16)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True, help_text='Markdown autorise.')),
                ('rules', models.TextField(blank=True, help_text='Regles de test. Markdown autorise.')),
                ('out_of_scope_notes', models.TextField(blank=True, help_text='Markdown autorise.')),
                ('safe_harbor', models.TextField(blank=True, help_text='Markdown autorise.')),
                ('disclosure_policy', models.TextField(blank=True, help_text='Markdown autorise.')),
                ('eligibility', models.TextField(blank=True, help_text="Conditions d'eligibilite. Markdown autorise.")),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('pgp_public_key', models.TextField(blank=True)),
                ('disclosure_delay_days', models.PositiveIntegerField(default=90, help_text='Delai par defaut avant divulgation coordonnee.')),
                ('requires_verified_email', models.BooleanField(default=True)),
                ('allows_anonymous_reports', models.BooleanField(default=True, help_text='Un VDP accepte generalement les signalements anonymes.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_programs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='organizations.organization')),
                ('sla_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='coordination.slapolicy')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
                'db_table': 'programs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('TESTING', 'Regle de test'), ('REPORTING', 'Regle de signalement'), ('PROHIBITED', 'Interdiction'), ('LEGAL', 'Cadre juridique')], default='TESTING', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_items', to='programs.program')),
            ],
            options={
                'verbose_name': 'Regle de programme',
                'verbose_name_plural': 'Regles de programme',
                'db_table': 'program_rules',
                'ordering': ['kind', 'position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProgramScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('in_scope', models.BooleanField(db_index=True, default=True)),
                ('target_type', models.CharField(choices=[('DOMAIN', 'Domaine / sous-domaine'), ('URL', 'URL'), ('IP_RANGE', 'IP ou plage CIDR'), ('MOBILE_APP', 'Application mobile'), ('API', 'API'), ('SOURCE_CODE', 'Code source'), ('OTHER', 'Autre')], default='DOMAIN', max_length=16)),
                ('identifier', models.CharField(help_text='Ex. *.gov.bf, api.exemple.bf, 10.0.0.0/24', max_length=255)),
                ('application', models.CharField(blank=True, max_length=180)),
                ('platform', models.CharField(blank=True, max_length=120)),
                ('environment', models.CharField(blank=True, help_text='Production, preproduction, test…', max_length=60)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('P1', 'P1 - Critique'), ('P2', 'P2 - Elevee'), ('P3', 'P3 - Moyenne'), ('P4', 'P4 - Faible')], default='P3', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='programs.program')),
            ],
            options={
                'verbose_name': 'Perimetre',
                'verbose_name_plural': 'Perimetres',
                'db_table': 'program_scopes',
                'ordering': ['-in_scope', 'priority', 'identifier'],
            },
        ),
        migrations.CreateModel(
            name='RewardPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(default='XOF', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('total_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_policy', to='programs.program')),
            ],
            options={
                'verbose_name': 'Politique de recompense',
                'verbose_name_plural': 'Politiques de recompense',
                'db_table': 'reward_policies',
            },
        ),
        migrations.CreateModel(
            name='RewardTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critique'), ('HIGH', 'Elevee'), ('MEDIUM', 'Moyenne'), ('LOW', 'Faible'), ('INFO', 'Informative')], max_length=16)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('description', models.CharField(blank=True, max_length=255)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='programs.rewardpolicy')),
            ],
            options={
                'verbose_name': 'Palier de recompense',
                'verbose_name_plural': 'Paliers de recompense',
                'db_table': 'reward_tiers',
                'ordering': ['-max_amount'],
            },
        ),
        migrations.AddIndex(
            model_name='program',
            index=models.Index(fields=['program_type', 'status'], name='programs_program_125f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='programscope',
            index=models.Index(fields=['program', 'in_scope'], name='program_sco_program_ec7c50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rewardtier',
            unique_together={('policy', 'severity')},
        ),
    ]
