# Generated by Django 5.2.17 on 2026-09-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="allows_anonymous_reports",
            field=models.BooleanField(
                default=True,
                help_text="Un VDP accepte generalement les signalements anonymes. Toujours desactive pour un programme Bug Bounty (une recompense exige un chercheur identifie).",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="requires_verified_email",
            field=models.BooleanField(
                default=False,
                help_text="Si active, seul un compte authentifie a l'email verifie peut signaler sur ce programme (incompatible avec l'anonymat).",
            ),
        ),
    ]
