# Generated by Django 5.2.17 on 2026-09-10 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewardtier',
            options={'ordering': [models.OrderBy(models.F('scope__identifier'), nulls_first=True), '-max_amount'], 'verbose_name': 'Palier de recompense', 'verbose_name_plural': 'Paliers de recompense'},
        ),
        migrations.AlterUniqueTogether(
            name='rewardtier',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rewardtier',
            name='scope',
            field=models.ForeignKey(blank=True, help_text='Vide : palier par defaut du programme. Renseigne : ce palier ne vaut que pour cet actif et prime sur le defaut.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reward_tiers', to='programs.programscope'),
        ),
        migrations.AddConstraint(
            model_name='rewardtier',
            constraint=models.UniqueConstraint(condition=models.Q(('scope__isnull', True)), fields=('policy', 'severity'), name='uniq_reward_tier_defaut'),
        ),
        migrations.AddConstraint(
            model_name='rewardtier',
            constraint=models.UniqueConstraint(condition=models.Q(('scope__isnull', False)), fields=('policy', 'scope', 'severity'), name='uniq_reward_tier_actif'),
        ),
    ]
