# Generated by Django 5.2.17 on 2026-09-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_program_allows_anonymous_reports_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='pgp_public_key',
            field=models.TextField(blank=True, help_text="Contact direct de l'organisation, hors plateforme eVDP. Le formulaire de signalement eVDP propose toujours la cle nationale, jamais celle-ci : chaque dossier doit rester lisible par le CSIRT national pour le triage."),
        ),
    ]
