# Generated by Django 5.2.17 on 2026-09-13 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0002_reward_tier_par_actif"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="allows_anonymous_reports",
            field=models.BooleanField(
                default=True,
                help_text="Un VDP accepte généralement les signalements anonymes.",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="confidentiality",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public"),
                    ("RESTRICTED", "Restreint"),
                    ("PRIVATE", "Privé (sur invitation)"),
                ],
                default="PUBLIC",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="description",
            field=models.TextField(blank=True, help_text="Markdown autorisé."),
        ),
        migrations.AlterField(
            model_name="program",
            name="disclosure_delay_days",
            field=models.PositiveIntegerField(
                default=90, help_text="Délai par défaut avant divulgation coordonnée."
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="disclosure_policy",
            field=models.TextField(blank=True, help_text="Markdown autorisé."),
        ),
        migrations.AlterField(
            model_name="program",
            name="eligibility",
            field=models.TextField(
                blank=True, help_text="Conditions d'éligibilité. Markdown autorisé."
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="out_of_scope_notes",
            field=models.TextField(blank=True, help_text="Markdown autorisé."),
        ),
        migrations.AlterField(
            model_name="program",
            name="rules",
            field=models.TextField(blank=True, help_text="Règles de test. Markdown autorisé."),
        ),
        migrations.AlterField(
            model_name="program",
            name="safe_harbor",
            field=models.TextField(blank=True, help_text="Markdown autorisé."),
        ),
        migrations.AlterField(
            model_name="program",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("ACTIVE", "Actif"),
                    ("PAUSED", "Suspendu"),
                    ("CLOSED", "Clôture"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="programrule",
            name="kind",
            field=models.CharField(
                choices=[
                    ("TESTING", "Règle de test"),
                    ("REPORTING", "Règle de signalement"),
                    ("PROHIBITED", "Interdiction"),
                    ("LEGAL", "Cadre juridique"),
                ],
                default="TESTING",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="programscope",
            name="priority",
            field=models.CharField(
                choices=[
                    ("P1", "P1 - Critique"),
                    ("P2", "P2 - Élevée"),
                    ("P3", "P3 - Moyenne"),
                    ("P4", "P4 - Faible"),
                ],
                default="P3",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="rewardtier",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                help_text="Vide : palier par défaut du programme. Renseigné : ce palier ne vaut que pour cet actif et prime sur le défaut.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reward_tiers",
                to="programs.programscope",
            ),
        ),
        migrations.AlterField(
            model_name="rewardtier",
            name="severity",
            field=models.CharField(
                choices=[
                    ("CRITICAL", "Critique"),
                    ("HIGH", "Élevée"),
                    ("MEDIUM", "Moyenne"),
                    ("LOW", "Faible"),
                    ("INFO", "Informative"),
                ],
                max_length=16,
            ),
        ),
    ]
