# Generated by Django 5.2.17 on 2026-09-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0003_clarify_pgp_key_help_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programrule",
            options={
                "ordering": ["kind", "position", "title"],
                "verbose_name": "Règle de programme",
                "verbose_name_plural": "Règles de programme",
            },
        ),
        migrations.AlterModelOptions(
            name="programscope",
            options={
                "ordering": ["-in_scope", "priority", "identifier"],
                "verbose_name": "Périmètre",
                "verbose_name_plural": "Périmètres",
            },
        ),
        migrations.AlterModelOptions(
            name="rewardpolicy",
            options={
                "verbose_name": "Politique de récompense",
                "verbose_name_plural": "Politiques de récompense",
            },
        ),
        migrations.AlterModelOptions(
            name="rewardtier",
            options={
                "ordering": ["-max_amount"],
                "verbose_name": "Palier de récompense",
                "verbose_name_plural": "Paliers de récompense",
            },
        ),
        migrations.AlterField(
            model_name="program",
            name="allows_anonymous_reports",
            field=models.BooleanField(
                default=True,
                help_text="Un VDP accepte généralement les signalements anonymes. Toujours désactivé pour un programme Bug Bounty (une récompense exige un chercheur identifié).",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="confidentiality",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Public"),
                    ("RESTRICTED", "Restreint"),
                    ("PRIVATE", "Privé (sur invitation)"),
                ],
                default="PUBLIC",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="description",
            field=models.TextField(blank=True, help_text="Markdown autorisé."),
        ),
        migrations.AlterField(
            model_name="program",
            name="disclosure_delay_days",
            field=models.PositiveIntegerField(
                default=90, help_text="Délai par défaut avant divulgation coordonnée."
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="disclosure_policy",
            field=models.TextField(blank=True, help_text="Markdown autorisé."),
        ),
        migrations.AlterField(
            model_name="program",
            name="eligibility",
            field=models.TextField(
                blank=True, help_text="Conditions d'éligibilité. Markdown autorisé."
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="out_of_scope_notes",
            field=models.TextField(blank=True, help_text="Markdown autorisé."),
        ),
        migrations.AlterField(
            model_name="program",
            name="pgp_public_key",
            field=models.TextField(
                blank=True,
                help_text="Contact direct de l'organisation, hors plateforme eVDP. Le formulaire de signalement eVDP propose toujours la clé nationale, jamais celle-ci : chaque dossier doit rester lisible par le CSIRT national pour le triage.",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="requires_verified_email",
            field=models.BooleanField(
                default=False,
                help_text="Si activé, seul un compte authentifié à l'email vérifié peut signaler sur ce programme (incompatible avec l'anonymat).",
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="rules",
            field=models.TextField(blank=True, help_text="Règles de test. Markdown autorisé."),
        ),
        migrations.AlterField(
            model_name="program",
            name="safe_harbor",
            field=models.TextField(blank=True, help_text="Markdown autorisé."),
        ),
        migrations.AlterField(
            model_name="program",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Brouillon"),
                    ("ACTIVE", "Actif"),
                    ("PAUSED", "Suspendu"),
                    ("CLOSED", "Clôturé"),
                ],
                db_index=True,
                default="DRAFT",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="programrule",
            name="kind",
            field=models.CharField(
                choices=[
                    ("TESTING", "Règle de test"),
                    ("REPORTING", "Règle de signalement"),
                    ("PROHIBITED", "Interdiction"),
                    ("LEGAL", "Cadre juridique"),
                ],
                default="TESTING",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="programscope",
            name="environment",
            field=models.CharField(
                blank=True, help_text="Production, préproduction, test…", max_length=60
            ),
        ),
        migrations.AlterField(
            model_name="programscope",
            name="priority",
            field=models.CharField(
                choices=[
                    ("P1", "P1 - Critique"),
                    ("P2", "P2 - Élevée"),
                    ("P3", "P3 - Moyenne"),
                    ("P4", "P4 - Faible"),
                ],
                default="P3",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="rewardtier",
            name="severity",
            field=models.CharField(
                choices=[
                    ("CRITICAL", "Critique"),
                    ("HIGH", "Élevée"),
                    ("MEDIUM", "Moyenne"),
                    ("LOW", "Faible"),
                    ("INFO", "Informative"),
                ],
                max_length=16,
            ),
        ),
    ]
