# Generated by Django 5.2.17 on 2026-09-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0003_alter_program_allows_anonymous_reports_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rewardpolicy",
            options={
                "verbose_name": "Politique de récompense",
                "verbose_name_plural": "Politiques de récompense",
            },
        ),
        migrations.AlterModelOptions(
            name="rewardtier",
            options={
                "ordering": [
                    models.OrderBy(models.F("scope__identifier"), nulls_first=True),
                    "-max_amount",
                ],
                "verbose_name": "Palier de récompense",
                "verbose_name_plural": "Paliers de récompense",
            },
        ),
    ]
