# Generated by Django 5.2.17 on 2026-10-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("programs", "0004_alter_rewardpolicy_options_alter_rewardtier_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programrule",
            options={
                "ordering": ["kind", "position", "title"],
                "verbose_name": "Règle de programme",
                "verbose_name_plural": "Règles de programme",
            },
        ),
        migrations.AlterModelOptions(
            name="programscope",
            options={
                "ordering": ["-in_scope", "priority", "identifier"],
                "verbose_name": "Périmètre",
                "verbose_name_plural": "Périmètres",
            },
        ),
        migrations.AlterField(
            model_name="programscope",
            name="environment",
            field=models.CharField(
                blank=True, help_text="Production, préproduction, test…", max_length=60
            ),
        ),
    ]
