# Generated by Django 5.2.17 on 2026-09-05 21:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearcherProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pseudonym', models.CharField(blank=True, db_index=True, max_length=60)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('country', models.CharField(default='Burkina Faso', max_length=80)),
                ('biography', models.TextField(blank=True, help_text='Markdown autorise.')),
                ('affiliation', models.CharField(blank=True, help_text='Organisation ou universite de rattachement.', max_length=180)),
                ('website', models.URLField(blank=True)),
                ('identity_mode', models.CharField(choices=[('PUBLIC', 'Identite publique'), ('PSEUDONYM', 'Pseudonyme'), ('PRIVATE', 'Anonyme')], default='PSEUDONYM', max_length=16)),
                ('is_public_profile', models.BooleanField(default=False, help_text="Apparait dans l'annuaire public des chercheurs.")),
                ('reputation', models.IntegerField(default=0, editable=False)),
                ('reports_submitted', models.PositiveIntegerField(default=0, editable=False)),
                ('reports_validated', models.PositiveIntegerField(default=0, editable=False)),
                ('critical_reports', models.PositiveIntegerField(default=0, editable=False)),
                ('total_rewards', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='researcher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil chercheur',
                'verbose_name_plural': 'Profils chercheurs',
                'db_table': 'researcher_profiles',
                'ordering': ['-reputation', 'pseudonym'],
            },
        ),
        migrations.CreateModel(
            name='ReputationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('VALIDATED', 'Rapport valide'), ('HIGH', 'Vulnerabilite High'), ('CRITICAL', 'Vulnerabilite Critical'), ('DUPLICATE', 'Rapport en doublon'), ('ABUSIVE', 'Rapport abusif'), ('MANUAL', 'Ajustement manuel')], max_length=24)),
                ('points', models.IntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reputation_events', to='coordination.case')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_reputation_events', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_events', to='researchers.researcherprofile')),
            ],
            options={
                'verbose_name': 'Evenement de reputation',
                'verbose_name_plural': 'Evenements de reputation',
                'db_table': 'reputation_events',
                'ordering': ['-created_at'],
            },
        ),
    ]
