# Generated by Django 5.2.17 on 2026-09-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reputationevent",
            name="reason",
            field=models.CharField(
                choices=[
                    ("VALIDATED", "Rapport validé"),
                    ("HIGH", "Vulnérabilité High"),
                    ("CRITICAL", "Vulnérabilité Critical"),
                    ("DUPLICATE", "Rapport en doublon"),
                    ("ABUSIVE", "Rapport abusif"),
                    ("MANUAL", "Ajustement manuel"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="researcherprofile",
            name="affiliation",
            field=models.CharField(
                blank=True,
                help_text="Organisation ou université de rattachement.",
                max_length=180,
            ),
        ),
        migrations.AlterField(
            model_name="researcherprofile",
            name="biography",
            field=models.TextField(blank=True, help_text="Markdown autorisé."),
        ),
        migrations.AlterField(
            model_name="researcherprofile",
            name="identity_mode",
            field=models.CharField(
                choices=[
                    ("PUBLIC", "Identité publique"),
                    ("PSEUDONYM", "Pseudonyme"),
                    ("PRIVATE", "Anonyme"),
                ],
                default="PSEUDONYM",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="researcherprofile",
            name="is_public_profile",
            field=models.BooleanField(
                default=False, help_text="Apparaît dans l'annuaire public des chercheurs."
            ),
        ),
    ]
