# Generated by Django 5.2.17 on 2026-09-16 19:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchers", "0002_alter_reputationevent_reason_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayoutProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "legal_full_name",
                    models.CharField(
                        blank=True,
                        help_text="Nom complet tel qu'il figure sur votre piece d'identite.",
                        max_length=150,
                    ),
                ),
                (
                    "id_document_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CNIB", "Carte Nationale d'Identite Burkinabe (CNIB)"),
                            ("PASSPORT", "Passeport"),
                            ("OTHER", "Autre piece d'identite"),
                        ],
                        max_length=16,
                    ),
                ),
                ("id_document_number", models.CharField(blank=True, max_length=60)),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Numero utilisable pour vous joindre au sujet d'un versement.",
                        max_length=32,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("country", models.CharField(default="Burkina Faso", max_length=80)),
                (
                    "accepted_terms",
                    models.BooleanField(
                        default=False,
                        help_text="Le chercheur atteste l'exactitude des informations fournies.",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil de versement",
                "verbose_name_plural": "Profils de versement",
                "db_table": "payout_profiles",
            },
        ),
        migrations.CreateModel(
            name="PayoutMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("BANK_TRANSFER", "Virement bancaire"),
                            ("MOBILE_MONEY", "Mobile money"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="Nom libre pour vous y retrouver.", max_length=80
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("bank_name", models.CharField(blank=True, max_length=150)),
                ("account_holder_name", models.CharField(blank=True, max_length=150)),
                (
                    "account_number",
                    models.CharField(
                        blank=True, help_text="IBAN ou numero de compte.", max_length=64
                    ),
                ),
                (
                    "mobile_operator",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ORANGE_MONEY", "Orange Money"),
                            ("MOOV_MONEY", "Moov Money"),
                            ("OTHER", "Autre operateur"),
                        ],
                        max_length=16,
                    ),
                ),
                ("mobile_number", models.CharField(blank=True, max_length=32)),
                ("mobile_holder_name", models.CharField(blank=True, max_length=150)),
                ("other_label", models.CharField(blank=True, max_length=120)),
                ("other_reference", models.CharField(blank=True, max_length=120)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="methods",
                        to="researchers.payoutprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Moyen de paiement",
                "verbose_name_plural": "Moyens de paiement",
                "db_table": "payout_methods",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
    ]
