# Generated by Django 5.2.17 on 2026-09-21 20:18

import apps.researchers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchers", "0002_payoutprofile_payoutmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="payoutprofile",
            name="id_document_content_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="payoutprofile",
            name="id_document_file",
            field=models.FileField(
                blank=True,
                max_length=300,
                upload_to=apps.researchers.models.payout_document_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="payoutprofile",
            name="id_document_original_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="payoutprofile",
            name="id_document_sha256",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="payoutprofile",
            name="id_document_size",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="payoutprofile",
            name="id_document_storage_name",
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name="payoutprofile",
            name="id_document_uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
