# Generated by Django 5.2.17 on 2026-09-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchers", "0003_payoutprofile_id_document_content_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payoutmethod",
            name="crypto_currency",
            field=models.CharField(blank=True, help_text="BTC, ETH, USDT…", max_length=16),
        ),
        migrations.AddField(
            model_name="payoutmethod",
            name="crypto_network",
            field=models.CharField(
                blank=True,
                help_text="Reseau/chaine (ex. Bitcoin, Ethereum ERC-20, Tron TRC-20). Un envoi sur le mauvais reseau est irrecuperable.",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="payoutmethod",
            name="crypto_wallet_address",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="payoutmethod",
            name="method_type",
            field=models.CharField(
                choices=[
                    ("BANK_TRANSFER", "Virement bancaire"),
                    ("MOBILE_MONEY", "Mobile money"),
                    ("CRYPTO", "Cryptomonnaie"),
                    ("OTHER", "Autre"),
                ],
                max_length=16,
            ),
        ),
    ]
