# Generated by Django 5.2.17 on 2026-09-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchers", "0004_payoutmethod_crypto_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payoutmethod",
            name="paypal_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="payoutmethod",
            name="method_type",
            field=models.CharField(
                choices=[
                    ("BANK_TRANSFER", "Virement bancaire"),
                    ("MOBILE_MONEY", "Mobile money"),
                    ("CRYPTO", "Cryptomonnaie"),
                    ("PAYPAL", "PayPal"),
                    ("OTHER", "Autre"),
                ],
                max_length=16,
            ),
        ),
    ]
