# Generated by Django 5.2.17 on 2026-09-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("researchers", "0006_payoutmethod_paypal_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payoutmethod",
            name="mobile_operator",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ORANGE_MONEY", "Orange Money"),
                    ("MOOV_MONEY", "Moov Money"),
                    ("TELECEL_MONEY", "Telecel Money"),
                    ("OTHER", "Autre operateur"),
                ],
                max_length=16,
            ),
        ),
    ]
