# Generated by Django 5.2.17 on 2026-09-30 21:56

import apps.core.fields
from django.db import migrations

from apps.core.fields import encrypted_field_names, rewrite_encrypted_fields

MODELS = ("PayoutProfile", "PayoutMethod")


def chiffrer(apps, schema_editor):
    """Les valeurs existantes sont lues en clair et reecrites chiffrees."""
    for name in MODELS:
        rewrite_encrypted_fields(apps.get_model("researchers", name))


def dechiffrer(apps, schema_editor):
    """Retour arriere : remet les valeurs en clair, en SQL brut pour que le
    champ ne les rechiffre pas au passage."""
    quote = schema_editor.quote_name
    connection = schema_editor.connection
    for name in MODELS:
        model = apps.get_model("researchers", name)
        names = encrypted_field_names(model)
        opts = model._meta
        columns = ", ".join(f"{quote(opts.get_field(n).column)} = %s" for n in names)
        # Identifiants tires des metadonnees du modele et quotes ; les valeurs
        # passent en parametres, jamais dans la chaine.
        sql = f"UPDATE {quote(opts.db_table)} SET {columns} WHERE {quote(opts.pk.column)} = %s"  # noqa: S608  # nosec B608
        for row in model.objects.values("pk", *names).iterator():
            pk = opts.pk.get_db_prep_value(row["pk"], connection)
            schema_editor.execute(sql, [row[n] for n in names] + [pk])


class Migration(migrations.Migration):
    dependencies = [
        ("researchers", "0007_alter_payoutmethod_mobile_operator"),
    ]

    operations = [
        # Les colonnes passent d'abord en TEXT (le chiffre depasse les
        # anciennes longueurs VARCHAR), puis les donnees sont chiffrees.
        migrations.AlterField(
            model_name="payoutmethod",
            name="account_holder_name",
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="payoutmethod",
            name="account_number",
            field=apps.core.fields.EncryptedCharField(
                blank=True, help_text="IBAN ou numero de compte.", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="payoutmethod",
            name="crypto_wallet_address",
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="payoutmethod",
            name="mobile_holder_name",
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="payoutmethod",
            name="mobile_number",
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="payoutmethod",
            name="other_reference",
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="payoutmethod",
            name="paypal_email",
            field=apps.core.fields.EncryptedEmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="payoutprofile",
            name="address",
            field=apps.core.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name="payoutprofile",
            name="contact_phone",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                help_text="Numero utilisable pour vous joindre au sujet d'un versement.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="payoutprofile",
            name="id_document_number",
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name="payoutprofile",
            name="id_document_original_filename",
            field=apps.core.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="payoutprofile",
            name="legal_full_name",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                help_text="Nom complet tel qu'il figure sur votre piece d'identite.",
                max_length=150,
            ),
        ),
        migrations.RunPython(chiffrer, dechiffrer),
    ]
