# Generated by Django 5.2.17 on 2026-10-01 01:02

import apps.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("researchers", "0008_chiffrement_donnees_versement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reputationevent",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Événement de réputation",
                "verbose_name_plural": "Événements de réputation",
            },
        ),
        migrations.AlterField(
            model_name="payoutmethod",
            name="account_number",
            field=apps.core.fields.EncryptedCharField(
                blank=True, help_text="IBAN ou numéro de compte.", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="payoutmethod",
            name="crypto_network",
            field=models.CharField(
                blank=True,
                help_text="Réseau/chaîne (ex. Bitcoin, Ethereum ERC-20, Tron TRC-20). Un envoi sur le mauvais réseau est irrécupérable.",
                max_length=60,
            ),
        ),
        migrations.AlterField(
            model_name="payoutmethod",
            name="mobile_operator",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ORANGE_MONEY", "Orange Money"),
                    ("MOOV_MONEY", "Moov Money"),
                    ("TELECEL_MONEY", "Telecel Money"),
                    ("OTHER", "Autre opérateur"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="payoutprofile",
            name="contact_phone",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                help_text="Numéro utilisable pour vous joindre au sujet d'un versement.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="payoutprofile",
            name="id_document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CNIB", "Carte Nationale d'Identité Burkinabè (CNIB)"),
                    ("PASSPORT", "Passeport"),
                    ("OTHER", "Autre pièce d'identité"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="payoutprofile",
            name="legal_full_name",
            field=apps.core.fields.EncryptedCharField(
                blank=True,
                help_text="Nom complet tel qu'il figure sur votre pièce d'identité.",
                max_length=150,
            ),
        ),
    ]
