# Generated by Django 5.2.17 on 2026-09-05 21:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_label', models.CharField(blank=True, help_text='Identite denormalisee, conservee si le compte est supprime.', max_length=254)),
                ('action', models.CharField(choices=[('LOGIN', 'Connexion'), ('LOGIN_FAILED', 'Echec de connexion'), ('LOGOUT', 'Deconnexion'), ('PASSWORD_RESET_REQUESTED', 'Reinitialisation demandee'), ('PASSWORD_CHANGED', 'Mot de passe modifie'), ('EMAIL_VERIFIED', 'Email verifie'), ('USER_CREATED', 'Utilisateur cree'), ('USER_UPDATED', 'Utilisateur modifie'), ('ROLE_CHANGED', 'Role modifie'), ('ORGANIZATION_CREATED', 'Organisation creee'), ('ORGANIZATION_UPDATED', 'Organisation modifiee'), ('MEMBERSHIP_CHANGED', 'Appartenance modifiee'), ('PROGRAM_CREATED', 'Programme cree'), ('PROGRAM_UPDATED', 'Programme modifie'), ('REPORT_SUBMITTED', 'Rapport soumis'), ('CASE_CREATED', 'Case cree'), ('CASE_VIEWED', 'Case consulte'), ('CASE_UPDATED', 'Case modifie'), ('CASE_ASSIGNED', 'Case assigne'), ('STATUS_CHANGED', 'Statut modifie'), ('MESSAGE_SENT', 'Message envoye'), ('ATTACHMENT_UPLOADED', 'Piece jointe televersee'), ('ATTACHMENT_DOWNLOADED', 'Piece jointe telechargee'), ('ATTACHMENT_DELETED', 'Piece jointe supprimee'), ('REPORT_VALIDATED', 'Rapport valide'), ('REPORT_REJECTED', 'Rapport rejete'), ('REPORT_DUPLICATED', 'Rapport marque doublon'), ('ADVISORY_CREATED', 'Advisory cree'), ('ADVISORY_UPDATED', 'Advisory modifie'), ('ADVISORY_PUBLISHED', 'Advisory publie'), ('ADVISORY_RETRACTED', 'Advisory retire'), ('BOUNTY_PROPOSED', 'Recompense proposee'), ('BOUNTY_APPROVED', 'Recompense approuvee'), ('BOUNTY_REJECTED', 'Recompense rejetee'), ('BOUNTY_PAID', 'Recompense payee'), ('EXPORT_GENERATED', 'Export genere'), ('PERMISSION_DENIED', 'Acces refuse'), ('SLA_BREACHED', 'SLA depasse'), ('CSAF_IMPORTED', 'Import CSAF')], db_index=True, max_length=48)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('result', models.CharField(choices=[('SUCCESS', 'Succes'), ('FAILURE', 'Echec'), ('DENIED', 'Refuse')], default='SUCCESS', max_length=12)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Entree d'audit",
                'verbose_name_plural': "Journal d'audit",
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='audit_logs_object__457405_idx'), models.Index(fields=['action', '-timestamp'], name='audit_logs_action_f48619_idx')],
            },
        ),
    ]
