# Generated by Django 5.2.17 on 2026-09-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Connexion"),
                    ("LOGIN_FAILED", "Echec de connexion"),
                    ("LOGOUT", "Deconnexion"),
                    ("PASSWORD_RESET_REQUESTED", "Reinitialisation demandee"),
                    ("PASSWORD_CHANGED", "Mot de passe modifie"),
                    ("EMAIL_VERIFIED", "Email verifie"),
                    ("USER_CREATED", "Utilisateur cree"),
                    ("USER_UPDATED", "Utilisateur modifie"),
                    ("ROLE_CHANGED", "Role modifie"),
                    ("ORGANIZATION_CREATED", "Organisation creee"),
                    ("ORGANIZATION_UPDATED", "Organisation modifiee"),
                    ("MEMBERSHIP_CHANGED", "Appartenance modifiee"),
                    ("PROGRAM_CREATED", "Programme cree"),
                    ("PROGRAM_UPDATED", "Programme modifie"),
                    ("REPORT_SUBMITTED", "Rapport soumis"),
                    ("CASE_CREATED", "Case cree"),
                    ("CASE_VIEWED", "Case consulte"),
                    ("CASE_UPDATED", "Case modifie"),
                    ("CASE_ASSIGNED", "Case assigne"),
                    ("STATUS_CHANGED", "Statut modifie"),
                    ("MESSAGE_SENT", "Message envoye"),
                    ("ATTACHMENT_UPLOADED", "Piece jointe televersee"),
                    ("ATTACHMENT_DOWNLOADED", "Piece jointe telechargee"),
                    ("ATTACHMENT_DELETED", "Piece jointe supprimee"),
                    ("REPORT_VALIDATED", "Rapport valide"),
                    ("REPORT_REJECTED", "Rapport rejete"),
                    ("REPORT_DUPLICATED", "Rapport marque doublon"),
                    ("ADVISORY_CREATED", "Advisory cree"),
                    ("ADVISORY_UPDATED", "Advisory modifie"),
                    ("ADVISORY_PUBLISHED", "Advisory publie"),
                    ("ADVISORY_RETRACTED", "Advisory retire"),
                    ("BOUNTY_PROPOSED", "Recompense proposee"),
                    ("BOUNTY_APPROVED", "Recompense approuvee"),
                    ("BOUNTY_REJECTED", "Recompense rejetee"),
                    ("BOUNTY_PAID", "Recompense payee"),
                    ("EXPORT_GENERATED", "Export genere"),
                    ("PERMISSION_DENIED", "Acces refuse"),
                    ("SLA_BREACHED", "SLA depasse"),
                    ("CSAF_IMPORTED", "Import CSAF"),
                    ("API_KEY_CREATED", "Cle d'API creee"),
                    ("API_KEY_REVOKED", "Cle d'API revoquee"),
                ],
                db_index=True,
                max_length=48,
            ),
        ),
    ]
