# Generated by Django 5.2.17 on 2026-09-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_actions_mfa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Connexion"),
                    ("LOGIN_FAILED", "Échec de connexion"),
                    ("LOGOUT", "Déconnexion"),
                    ("PASSWORD_RESET_REQUESTED", "Réinitialisation demandee"),
                    ("PASSWORD_CHANGED", "Mot de passe modifié"),
                    ("EMAIL_VERIFIED", "Email vérifié"),
                    ("MFA_ENROLLED", "Double authentification activée"),
                    ("MFA_VERIFIED", "Second facteur validé"),
                    ("MFA_FAILED", "Second facteur refusé"),
                    ("MFA_RESET", "Double authentification réinitialisée"),
                    ("USER_CREATED", "Utilisateur créé"),
                    ("USER_UPDATED", "Utilisateur modifié"),
                    ("ROLE_CHANGED", "Rôle modifié"),
                    ("ORGANIZATION_CREATED", "Organisation créée"),
                    ("ORGANIZATION_UPDATED", "Organisation modifiée"),
                    ("MEMBERSHIP_CHANGED", "Appartenance modifiée"),
                    ("PROGRAM_CREATED", "Programme créé"),
                    ("PROGRAM_UPDATED", "Programme modifié"),
                    ("REPORT_SUBMITTED", "Rapport soumis"),
                    ("CASE_CREATED", "Case créé"),
                    ("CASE_VIEWED", "Case consulte"),
                    ("CASE_UPDATED", "Case modifié"),
                    ("CASE_ASSIGNED", "Case assigné"),
                    ("STATUS_CHANGED", "Statut modifié"),
                    ("MESSAGE_SENT", "Message envoyé"),
                    ("ATTACHMENT_UPLOADED", "Pièce jointe téléversée"),
                    ("ATTACHMENT_DOWNLOADED", "Pièce jointe téléchargée"),
                    ("ATTACHMENT_DELETED", "Pièce jointe supprimée"),
                    ("REPORT_VALIDATED", "Rapport validé"),
                    ("REPORT_REJECTED", "Rapport rejeté"),
                    ("REPORT_DUPLICATED", "Rapport marqué doublon"),
                    ("ADVISORY_CREATED", "Advisory créé"),
                    ("ADVISORY_UPDATED", "Advisory modifié"),
                    ("ADVISORY_PUBLISHED", "Advisory publié"),
                    ("ADVISORY_RETRACTED", "Advisory retiré"),
                    ("BOUNTY_PROPOSED", "Récompense proposée"),
                    ("BOUNTY_APPROVED", "Récompense approuvée"),
                    ("BOUNTY_REJECTED", "Récompense rejetée"),
                    ("BOUNTY_PAID", "Récompense payée"),
                    ("EXPORT_GENERATED", "Export généré"),
                    ("PERMISSION_DENIED", "Accès refusé"),
                    ("SLA_BREACHED", "SLA dépassé"),
                    ("CSAF_IMPORTED", "Import CSAF"),
                ],
                db_index=True,
                max_length=48,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="actor_label",
            field=models.CharField(
                blank=True,
                help_text="Identité dénormalisée, conservée si le compte est supprimé.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="result",
            field=models.CharField(
                choices=[("SUCCESS", "Succès"), ("FAILURE", "Échec"), ("DENIED", "Refusé")],
                default="SUCCESS",
                max_length=12,
            ),
        ),
    ]
