# Generated by Django 5.2.17 on 2026-09-05 21:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Assignation',
                'verbose_name_plural': 'Assignations',
                'db_table': 'case_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(help_text='Markdown autorise.')),
                ('confidentiality', models.CharField(choices=[('PARTICIPANTS', 'Participants du case'), ('INTERNAL', 'Interne CSIRT'), ('RESTRICTED', 'Restreint (coordination nationale)')], db_index=True, default='PARTICIPANTS', max_length=16)),
                ('is_system', models.BooleanField(default=False)),
                ('content_hash', models.CharField(blank=True, editable=False, help_text="SHA-256 du contenu : preuve d'integrite du fil de discussion.", max_length=64)),
                ('is_pgp_encrypted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message de case',
                'verbose_name_plural': 'Messages de case',
                'db_table': 'case_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participant_role', models.CharField(choices=[('REPORTER', 'Declarant'), ('ANALYST', 'Analyste CSIRT'), ('COORDINATOR', 'Coordinateur'), ('ORGANIZATION', 'Organisation affectee'), ('DSI', 'DSI'), ('OBSERVER', 'Observateur')], default='OBSERVER', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'db_table': 'case_participants',
                'ordering': ['participant_role', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('RECEIVED', 'Recu'), ('TRIAGE', 'En triage'), ('NEEDS_INFORMATION', 'Informations demandees'), ('ACKNOWLEDGED', 'Accuse de reception'), ('VALIDATED', 'Valide'), ('SEVERITY_ASSIGNED', 'Severite attribuee'), ('BOUNTY_REVIEW', 'Revue de recompense'), ('REWARD_APPROVED', 'Recompense approuvee'), ('DUPLICATE', 'Doublon'), ('REJECTED', 'Rejete'), ('OUT_OF_SCOPE', 'Hors perimetre'), ('NOT_APPLICABLE', 'Non applicable'), ('INFORMATIVE', 'Informatif'), ('IN_PROGRESS', 'En cours de traitement'), ('VENDOR_CONTACTED', 'Organisation contactee'), ('VENDOR_ACKNOWLEDGED', 'Organisation a accuse reception'), ('REMEDIATION', 'Remediation en cours'), ('FIX_AVAILABLE', 'Correctif disponible'), ('VERIFICATION', 'Verification du correctif'), ('FIX_VERIFIED', 'Correctif verifie'), ('DISCLOSURE_SCHEDULED', 'Divulgation planifiee'), ('PUBLISHED', 'Publie'), ('CLOSED', 'Clos')], max_length=24)),
                ('to_status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('RECEIVED', 'Recu'), ('TRIAGE', 'En triage'), ('NEEDS_INFORMATION', 'Informations demandees'), ('ACKNOWLEDGED', 'Accuse de reception'), ('VALIDATED', 'Valide'), ('SEVERITY_ASSIGNED', 'Severite attribuee'), ('BOUNTY_REVIEW', 'Revue de recompense'), ('REWARD_APPROVED', 'Recompense approuvee'), ('DUPLICATE', 'Doublon'), ('REJECTED', 'Rejete'), ('OUT_OF_SCOPE', 'Hors perimetre'), ('NOT_APPLICABLE', 'Non applicable'), ('INFORMATIVE', 'Informatif'), ('IN_PROGRESS', 'En cours de traitement'), ('VENDOR_CONTACTED', 'Organisation contactee'), ('VENDOR_ACKNOWLEDGED', 'Organisation a accuse reception'), ('REMEDIATION', 'Remediation en cours'), ('FIX_AVAILABLE', 'Correctif disponible'), ('VERIFICATION', 'Verification du correctif'), ('FIX_VERIFIED', 'Correctif verifie'), ('DISCLOSURE_SCHEDULED', 'Divulgation planifiee'), ('PUBLISHED', 'Publie'), ('CLOSED', 'Clos')], max_length=24)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Historique de statut',
                'verbose_name_plural': 'Historique des statuts',
                'db_table': 'case_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseTimelineEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('REPORT_RECEIVED', 'Rapport recu'), ('ACKNOWLEDGED', 'Accuse de reception'), ('TRIAGE_STARTED', 'Triage engage'), ('INFORMATION_REQUESTED', 'Informations demandees'), ('VALIDATED', 'Vulnerabilite validee'), ('SEVERITY_SET', 'Severite attribuee'), ('ORGANIZATION_CONTACTED', 'Organisation contactee'), ('ORGANIZATION_ACKNOWLEDGED', 'Organisation a repondu'), ('FIX_PROVIDED', 'Correctif fourni'), ('FIX_VERIFIED', 'Correctif verifie'), ('DISCLOSURE_SCHEDULED', 'Divulgation planifiee'), ('ADVISORY_PUBLISHED', 'Advisory publie'), ('REWARD_APPROVED', 'Recompense approuvee'), ('DUPLICATE_MARKED', 'Doublon identifie'), ('REJECTED', 'Rapport rejete'), ('CLOSED', 'Case clos'), ('STATUS_CHANGED', 'Changement de statut'), ('ASSIGNED', 'Assignation'), ('NOTE', 'Note')], default='NOTE', max_length=32)),
                ('label', models.CharField(max_length=255)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_public', models.BooleanField(default=False, help_text='Seuls les evenements publics peuvent alimenter un advisory.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Evenement de chronologie',
                'verbose_name_plural': 'Chronologie',
                'db_table': 'case_timeline_events',
                'ordering': ['occurred_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SLAEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('ACKNOWLEDGEMENT', 'Accuse de reception'), ('TRIAGE', 'Premier triage'), ('VENDOR_RESPONSE', "Reponse de l'organisation"), ('REMEDIATION', 'Remediation'), ('DISCLOSURE', 'Divulgation')], max_length=24)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('state', models.CharField(choices=[('PENDING', 'En cours'), ('APPROACHING', 'Echeance proche'), ('MET', 'Respecte'), ('BREACHED', 'Depasse'), ('CANCELLED', 'Annule')], db_index=True, default='PENDING', max_length=16)),
                ('satisfied_at', models.DateTimeField(blank=True, null=True)),
                ('warned_at', models.DateTimeField(blank=True, null=True)),
                ('breached_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Echeance SLA',
                'verbose_name_plural': 'Echeances SLA',
                'db_table': 'sla_events',
                'ordering': ['due_at'],
            },
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('acknowledgement_hours', models.PositiveIntegerField(default=72)),
                ('triage_days', models.PositiveIntegerField(default=5)),
                ('vendor_response_days', models.PositiveIntegerField(default=7)),
                ('remediation_days_critical', models.PositiveIntegerField(default=30)),
                ('remediation_days_high', models.PositiveIntegerField(default=30)),
                ('remediation_days_medium', models.PositiveIntegerField(default=60)),
                ('remediation_days_low', models.PositiveIntegerField(default=90)),
                ('disclosure_delay_days', models.PositiveIntegerField(default=90)),
                ('warning_ratio', models.PositiveSmallIntegerField(default=80, help_text='Pourcentage du delai a partir duquel une alerte est levee.')),
            ],
            options={
                'verbose_name': 'Politique SLA',
                'verbose_name_plural': 'Politiques SLA',
                'db_table': 'sla_policies',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_id', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('workflow', models.CharField(choices=[('VDP', 'Divulgation coordonnee (CVD)'), ('BUG_BOUNTY', 'Bug Bounty')], default='VDP', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('product', models.CharField(blank=True, max_length=200)),
                ('vulnerability_type', models.CharField(choices=[('AUTHENTICATION', 'Authentification'), ('AUTHORIZATION', "Autorisation / controle d'acces"), ('XSS', 'Cross-Site Scripting (XSS)'), ('SQLI', 'Injection SQL'), ('SSRF', 'Server-Side Request Forgery (SSRF)'), ('RCE', 'Execution de code a distance (RCE)'), ('LFI_RFI', 'Inclusion de fichier (LFI/RFI)'), ('IDOR', 'Reference directe non securisee (IDOR)'), ('CSRF', 'Cross-Site Request Forgery (CSRF)'), ('INFO_DISCLOSURE', "Divulgation d'information"), ('MISCONFIGURATION', 'Mauvaise configuration'), ('CRYPTO', 'Probleme cryptographique'), ('BUSINESS_LOGIC', 'Logique metier'), ('API_SECURITY', 'Securite des API'), ('MOBILE', 'Application mobile'), ('CLOUD', 'Cloud'), ('NETWORK', 'Reseau / infrastructure'), ('OTHER', 'Autre')], default='OTHER', max_length=24)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critique'), ('HIGH', 'Elevee'), ('MEDIUM', 'Moyenne'), ('LOW', 'Faible'), ('INFO', 'Informative')], db_index=True, default='MEDIUM', max_length=16)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('cvss_vector', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis'), ('RECEIVED', 'Recu'), ('TRIAGE', 'En triage'), ('NEEDS_INFORMATION', 'Informations demandees'), ('ACKNOWLEDGED', 'Accuse de reception'), ('VALIDATED', 'Valide'), ('SEVERITY_ASSIGNED', 'Severite attribuee'), ('BOUNTY_REVIEW', 'Revue de recompense'), ('REWARD_APPROVED', 'Recompense approuvee'), ('DUPLICATE', 'Doublon'), ('REJECTED', 'Rejete'), ('OUT_OF_SCOPE', 'Hors perimetre'), ('NOT_APPLICABLE', 'Non applicable'), ('INFORMATIVE', 'Informatif'), ('IN_PROGRESS', 'En cours de traitement'), ('VENDOR_CONTACTED', 'Organisation contactee'), ('VENDOR_ACKNOWLEDGED', 'Organisation a accuse reception'), ('REMEDIATION', 'Remediation en cours'), ('FIX_AVAILABLE', 'Correctif disponible'), ('VERIFICATION', 'Verification du correctif'), ('FIX_VERIFIED', 'Correctif verifie'), ('DISCLOSURE_SCHEDULED', 'Divulgation planifiee'), ('PUBLISHED', 'Publie'), ('CLOSED', 'Clos')], db_index=True, default='SUBMITTED', max_length=24)),
                ('priority_score', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('remediated_at', models.DateTimeField(blank=True, null=True)),
                ('disclosure_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
    ]
