# Generated by Django 5.2.17 on 2026-09-05 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordination', '0001_initial'),
        ('organizations', '0001_initial'),
        ('programs', '0001_initial'),
        ('reports', '0001_initial'),
        ('vulnerabilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='cve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='vulnerabilities.cve'),
        ),
        migrations.AddField(
            model_name='case',
            name='cwe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='vulnerabilities.cwe'),
        ),
        migrations.AddField(
            model_name='case',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='coordination.case'),
        ),
        migrations.AddField(
            model_name='case',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='case',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='programs.program'),
        ),
        migrations.AddField(
            model_name='case',
            name='report',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='case', to='reports.vulnerabilityreport'),
        ),
        migrations.AddField(
            model_name='case',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_assignments_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='coordination.case'),
        ),
        migrations.AddField(
            model_name='caseassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casemessage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casemessage',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='coordination.case'),
        ),
        migrations.AddField(
            model_name='caseparticipant',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_participants_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caseparticipant',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='coordination.case'),
        ),
        migrations.AddField(
            model_name='caseparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casestatushistory',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casestatushistory',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='coordination.case'),
        ),
        migrations.AddField(
            model_name='casetimelineevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casetimelineevent',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='coordination.case'),
        ),
        migrations.AddField(
            model_name='slaevent',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_events', to='coordination.case'),
        ),
        migrations.AddField(
            model_name='slaevent',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='coordination.slapolicy'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', 'severity'], name='cases_status_54634f_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['organization', 'status'], name='cases_organiz_825e54_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['-priority_score', '-created_at'], name='cases_priorit_5fa2d6_idx'),
        ),
        migrations.AddIndex(
            model_name='casemessage',
            index=models.Index(fields=['case', 'created_at'], name='case_messag_case_id_b02fc8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caseparticipant',
            unique_together={('case', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='slaevent',
            unique_together={('case', 'kind')},
        ),
    ]
