# Generated by Django 5.2.17 on 2026-09-09 17:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coordination", "0003_default_sla_policy"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseTrackingToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("access_count", models.PositiveIntegerField(default=0)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_token",
                        to="coordination.case",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jeton de suivi",
                "verbose_name_plural": "Jetons de suivi",
                "db_table": "case_tracking_tokens",
            },
        ),
    ]
