# Generated by Django 5.2.17 on 2026-09-10 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coordination', '0003_default_sla_policy'),
        ('programs', '0002_reward_tier_par_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='scope',
            field=models.ForeignKey(blank=True, help_text="Actif du perimetre concerne, retenu au triage. Determine la grille de recompense lorsqu'elle varie par actif.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='programs.programscope'),
        ),
    ]
