# Generated by Django 5.2.17 on 2026-09-24 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coordination", "0006_casetrackingtoken"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="admissibility_attachment_ok",
            field=models.BooleanField(default=False, verbose_name="Pièce jointe lisible"),
        ),
        migrations.AddField(
            model_name="case",
            name="admissibility_organization_ok",
            field=models.BooleanField(default=False, verbose_name="Organisation identifiée"),
        ),
        migrations.AddField(
            model_name="case",
            name="admissibility_scope_ok",
            field=models.BooleanField(default=False, verbose_name="Périmètre vérifié"),
        ),
        migrations.AddField(
            model_name="case",
            name="bounty_status",
            field=models.CharField(
                choices=[
                    ("UNDETERMINED", "Non déterminé"),
                    ("NOT_ELIGIBLE", "Non éligible"),
                    ("BOUNTY_ELIGIBLE", "Éligible à une prime"),
                    ("BOUNTY_PROPOSED", "Prime proposée"),
                    ("BOUNTY_CREDITED", "Prime créditée"),
                ],
                db_index=True,
                default="UNDETERMINED",
                help_text="Branche prime, indépendante du statut du dossier.",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="cvss_set_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Analyste auteur de la qualification (règle des quatre yeux).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="qualified_cases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="fix_description",
            field=models.TextField(blank=True, verbose_name="Description du correctif"),
        ),
        migrations.AddField(
            model_name="case",
            name="fix_verification_notes",
            field=models.TextField(
                blank=True, verbose_name="Compte rendu de contre-vérification"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="fix_version",
            field=models.CharField(
                blank=True,
                max_length=120,
                verbose_name="Version ou date de déploiement du correctif",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="remediation_due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date cible du correctif"
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="remediation_plan",
            field=models.TextField(blank=True, verbose_name="Plan de remédiation"),
        ),
        migrations.AddField(
            model_name="case",
            name="status_before_exception",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUBMITTED", "Soumis"),
                    ("ACKNOWLEDGED", "Accusé de réception"),
                    ("IN_ANALYSIS", "En analyse"),
                    ("VALIDATION_PENDING", "Qualification à valider"),
                    ("VALIDATED", "Validé"),
                    ("VENDOR_NOTIFIED", "Organisation notifiée"),
                    ("REMEDIATION_IN_PROGRESS", "Remédiation en cours"),
                    ("FIX_AVAILABLE", "Correctif disponible"),
                    ("FIX_VERIFIED", "Correctif vérifié"),
                    ("ADVISORY_REVIEW", "Advisory en relecture"),
                    ("CLOSED", "Clos"),
                    ("NEEDS_INFORMATION", "Compléments demandés"),
                    ("REJECTION_PENDING", "Rejet proposé"),
                    ("REJECTED", "Rejeté"),
                    ("DUPLICATE", "Doublon"),
                ],
                help_text="Étape d'origine à laquelle revient une sortie d'exception.",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="vendor_summary",
            field=models.TextField(
                blank=True,
                help_text="Transmise à l'organisation ; l'identité du déclarant y est protégée selon le mode qu'il a choisi.",
                verbose_name="Version « organisation » du rapport",
            ),
        ),
        migrations.AddField(
            model_name="slaevent",
            name="suspended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="slapolicy",
            name="validation_days",
            field=models.PositiveIntegerField(
                default=2, help_text="Validation de la qualification (étape 4)."
            ),
        ),
        migrations.AddField(
            model_name="slapolicy",
            name="verification_days",
            field=models.PositiveIntegerField(
                default=5, help_text="Contre-vérification du correctif (étape 8)."
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Soumis"),
                    ("ACKNOWLEDGED", "Accusé de réception"),
                    ("IN_ANALYSIS", "En analyse"),
                    ("VALIDATION_PENDING", "Qualification à valider"),
                    ("VALIDATED", "Validé"),
                    ("VENDOR_NOTIFIED", "Organisation notifiée"),
                    ("REMEDIATION_IN_PROGRESS", "Remédiation en cours"),
                    ("FIX_AVAILABLE", "Correctif disponible"),
                    ("FIX_VERIFIED", "Correctif vérifié"),
                    ("ADVISORY_REVIEW", "Advisory en relecture"),
                    ("CLOSED", "Clos"),
                    ("NEEDS_INFORMATION", "Compléments demandés"),
                    ("REJECTION_PENDING", "Rejet proposé"),
                    ("REJECTED", "Rejeté"),
                    ("DUPLICATE", "Doublon"),
                ],
                db_index=True,
                default="SUBMITTED",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="casemessage",
            name="confidentiality",
            field=models.CharField(
                choices=[
                    ("PARTICIPANTS", "Canal chercheur"),
                    ("ORGANIZATION", "Canal CSIRT ↔ organisation"),
                    ("INTERNAL", "Interne CSIRT (notes de triage et d'analyse)"),
                    ("RESTRICTED", "Restreint (coordination nationale)"),
                ],
                db_index=True,
                default="PARTICIPANTS",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="casestatushistory",
            name="from_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUBMITTED", "Soumis"),
                    ("ACKNOWLEDGED", "Accusé de réception"),
                    ("IN_ANALYSIS", "En analyse"),
                    ("VALIDATION_PENDING", "Qualification à valider"),
                    ("VALIDATED", "Validé"),
                    ("VENDOR_NOTIFIED", "Organisation notifiée"),
                    ("REMEDIATION_IN_PROGRESS", "Remédiation en cours"),
                    ("FIX_AVAILABLE", "Correctif disponible"),
                    ("FIX_VERIFIED", "Correctif vérifié"),
                    ("ADVISORY_REVIEW", "Advisory en relecture"),
                    ("CLOSED", "Clos"),
                    ("NEEDS_INFORMATION", "Compléments demandés"),
                    ("REJECTION_PENDING", "Rejet proposé"),
                    ("REJECTED", "Rejeté"),
                    ("DUPLICATE", "Doublon"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="casestatushistory",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Soumis"),
                    ("ACKNOWLEDGED", "Accusé de réception"),
                    ("IN_ANALYSIS", "En analyse"),
                    ("VALIDATION_PENDING", "Qualification à valider"),
                    ("VALIDATED", "Validé"),
                    ("VENDOR_NOTIFIED", "Organisation notifiée"),
                    ("REMEDIATION_IN_PROGRESS", "Remédiation en cours"),
                    ("FIX_AVAILABLE", "Correctif disponible"),
                    ("FIX_VERIFIED", "Correctif vérifié"),
                    ("ADVISORY_REVIEW", "Advisory en relecture"),
                    ("CLOSED", "Clos"),
                    ("NEEDS_INFORMATION", "Compléments demandés"),
                    ("REJECTION_PENDING", "Rejet proposé"),
                    ("REJECTED", "Rejeté"),
                    ("DUPLICATE", "Doublon"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="casetimelineevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("REPORT_RECEIVED", "Rapport reçu"),
                    ("ACKNOWLEDGED", "Accusé de réception"),
                    ("TRIAGE_STARTED", "Déclaré recevable"),
                    ("QUALIFICATION_SUBMITTED", "Qualification soumise"),
                    ("INFORMATION_REQUESTED", "Informations demandées"),
                    ("VALIDATED", "Vulnérabilité validée"),
                    ("SEVERITY_SET", "Sévérité attribuée"),
                    ("ORGANIZATION_CONTACTED", "Organisation contactée"),
                    ("ORGANIZATION_ACKNOWLEDGED", "Organisation a répondu"),
                    ("REMEDIATION_PLANNED", "Plan de remédiation accepté"),
                    ("FIX_PROVIDED", "Correctif fourni"),
                    ("FIX_VERIFIED", "Correctif vérifié"),
                    ("DISCLOSURE_SCHEDULED", "Divulgation planifiée"),
                    ("ADVISORY_SUBMITTED", "Advisory soumis en relecture"),
                    ("ADVISORY_PUBLISHED", "Advisory publié"),
                    ("REWARD_APPROVED", "Récompense approuvée"),
                    ("DUPLICATE_MARKED", "Doublon identifié"),
                    ("REJECTION_PROPOSED", "Rejet proposé"),
                    ("REJECTED", "Rapport rejeté"),
                    ("SENT_BACK", "Renvoyé à l'auteur"),
                    ("ESCALATED", "Escalade"),
                    ("CLOSED", "Case clos"),
                    ("STATUS_CHANGED", "Changement de statut"),
                    ("ASSIGNED", "Assignation"),
                    ("NOTE", "Note"),
                ],
                default="NOTE",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="slaevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ACKNOWLEDGEMENT", "Accusé de réception"),
                    ("TRIAGE", "Recevabilité et qualification"),
                    ("VALIDATION", "Validation de la qualification"),
                    ("VENDOR_RESPONSE", "Plan de remédiation de l'organisation"),
                    ("REMEDIATION", "Remédiation"),
                    ("VERIFICATION", "Contre-vérification du correctif"),
                    ("DISCLOSURE", "Divulgation"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="slaevent",
            name="state",
            field=models.CharField(
                choices=[
                    ("PENDING", "En cours"),
                    ("APPROACHING", "Échéance proche"),
                    ("SUSPENDED", "Suspendu (compléments demandés)"),
                    ("MET", "Respecte"),
                    ("BREACHED", "Dépassé"),
                    ("CANCELLED", "Annulé"),
                ],
                db_index=True,
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="slapolicy",
            name="remediation_days_high",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name="slapolicy",
            name="remediation_days_medium",
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AlterField(
            model_name="slapolicy",
            name="triage_days",
            field=models.PositiveIntegerField(
                default=5, help_text="Recevabilité et qualification (étapes 2 et 3)."
            ),
        ),
        migrations.AlterField(
            model_name="slapolicy",
            name="vendor_response_days",
            field=models.PositiveIntegerField(
                default=5, help_text="Plan de remédiation de l'organisation (étape 6)."
            ),
        ),
        migrations.AlterField(
            model_name="slapolicy",
            name="warning_ratio",
            field=models.PositiveSmallIntegerField(
                default=75,
                help_text="Pourcentage du délai à partir duquel une alerte est levée.",
            ),
        ),
    ]
