# Generated by Django 5.2.17 on 2026-09-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coordination", "0006_casetrackingtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="admissibility_checklist",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="case",
            name="bounty_stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("BOUNTY_ELIGIBLE", "Éligible à une prime"),
                    ("BOUNTY_PROPOSED", "Prime proposée"),
                    ("BOUNTY_CREDITED", "Prime créditée"),
                    ("NOT_ELIGIBLE", "Non éligible"),
                ],
                db_index=True,
                default="",
                help_text="Statut de prime, distinct du statut du dossier.",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="deadline_disclosure_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Divulgation à échéance décidée par le Coordinateur.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="fix_deployed_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="fix_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="case",
            name="fix_version",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="case",
            name="remediation_plan",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="case",
            name="remediation_target_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="return_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUBMITTED", "Soumis"),
                    ("ACKNOWLEDGED", "Réception accusée"),
                    ("IN_ANALYSIS", "En analyse"),
                    ("VALIDATION_PENDING", "Qualification à valider"),
                    ("VALIDATED", "Validé"),
                    ("VENDOR_NOTIFIED", "Organisation notifiée"),
                    ("REMEDIATION_IN_PROGRESS", "Remédiation en cours"),
                    ("FIX_AVAILABLE", "Correctif disponible"),
                    ("FIX_VERIFIED", "Correctif vérifié"),
                    ("ADVISORY_REVIEW", "Advisory en relecture"),
                    ("CLOSED", "Clos"),
                    ("NEEDS_INFORMATION", "Compléments demandés"),
                    ("REJECTION_PENDING", "Rejet proposé"),
                    ("REJECTED", "Rejeté"),
                    ("DUPLICATE", "Doublon"),
                ],
                help_text="Étape d'origine à retrouver après des compléments ou un rejet renvoyé.",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="sla_paused_at",
            field=models.DateTimeField(
                blank=True,
                help_text="SLA suspendu pendant une demande de compléments.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="vendor_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="case",
            name="verification_report",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="slapolicy",
            name="validation_days",
            field=models.PositiveIntegerField(
                default=2, help_text="Étape 4 : validation de la qualification."
            ),
        ),
        migrations.AddField(
            model_name="slapolicy",
            name="verification_days",
            field=models.PositiveIntegerField(
                default=5, help_text="Étape 8 : contre-vérification du correctif."
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="cvss_vector",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Soumis"),
                    ("ACKNOWLEDGED", "Réception accusée"),
                    ("IN_ANALYSIS", "En analyse"),
                    ("VALIDATION_PENDING", "Qualification à valider"),
                    ("VALIDATED", "Validé"),
                    ("VENDOR_NOTIFIED", "Organisation notifiée"),
                    ("REMEDIATION_IN_PROGRESS", "Remédiation en cours"),
                    ("FIX_AVAILABLE", "Correctif disponible"),
                    ("FIX_VERIFIED", "Correctif vérifié"),
                    ("ADVISORY_REVIEW", "Advisory en relecture"),
                    ("CLOSED", "Clos"),
                    ("NEEDS_INFORMATION", "Compléments demandés"),
                    ("REJECTION_PENDING", "Rejet proposé"),
                    ("REJECTED", "Rejeté"),
                    ("DUPLICATE", "Doublon"),
                ],
                db_index=True,
                default="SUBMITTED",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="casemessage",
            name="confidentiality",
            field=models.CharField(
                choices=[
                    ("RESEARCHER", "Canal chercheur"),
                    ("ORGANIZATION", "Canal CSIRT ↔ organisation"),
                    ("INTERNAL", "Notes de triage et d'analyse"),
                ],
                db_index=True,
                default="RESEARCHER",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="casestatushistory",
            name="from_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SUBMITTED", "Soumis"),
                    ("ACKNOWLEDGED", "Réception accusée"),
                    ("IN_ANALYSIS", "En analyse"),
                    ("VALIDATION_PENDING", "Qualification à valider"),
                    ("VALIDATED", "Validé"),
                    ("VENDOR_NOTIFIED", "Organisation notifiée"),
                    ("REMEDIATION_IN_PROGRESS", "Remédiation en cours"),
                    ("FIX_AVAILABLE", "Correctif disponible"),
                    ("FIX_VERIFIED", "Correctif vérifié"),
                    ("ADVISORY_REVIEW", "Advisory en relecture"),
                    ("CLOSED", "Clos"),
                    ("NEEDS_INFORMATION", "Compléments demandés"),
                    ("REJECTION_PENDING", "Rejet proposé"),
                    ("REJECTED", "Rejeté"),
                    ("DUPLICATE", "Doublon"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="casestatushistory",
            name="to_status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Soumis"),
                    ("ACKNOWLEDGED", "Réception accusée"),
                    ("IN_ANALYSIS", "En analyse"),
                    ("VALIDATION_PENDING", "Qualification à valider"),
                    ("VALIDATED", "Validé"),
                    ("VENDOR_NOTIFIED", "Organisation notifiée"),
                    ("REMEDIATION_IN_PROGRESS", "Remédiation en cours"),
                    ("FIX_AVAILABLE", "Correctif disponible"),
                    ("FIX_VERIFIED", "Correctif vérifié"),
                    ("ADVISORY_REVIEW", "Advisory en relecture"),
                    ("CLOSED", "Clos"),
                    ("NEEDS_INFORMATION", "Compléments demandés"),
                    ("REJECTION_PENDING", "Rejet proposé"),
                    ("REJECTED", "Rejeté"),
                    ("DUPLICATE", "Doublon"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="casetimelineevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("REPORT_RECEIVED", "Rapport reçu"),
                    ("ACKNOWLEDGED", "Accusé de réception"),
                    ("TRIAGE_STARTED", "Rapport déclaré recevable"),
                    ("INFORMATION_REQUESTED", "Informations demandées"),
                    ("INFORMATION_PROVIDED", "Compléments reçus"),
                    ("QUALIFICATION_SUBMITTED", "Qualification soumise"),
                    ("VALIDATED", "Vulnérabilité validée"),
                    ("SEVERITY_SET", "Sévérité attribuée"),
                    ("ORGANIZATION_CONTACTED", "Organisation contactée"),
                    ("ORGANIZATION_ACKNOWLEDGED", "Plan de remédiation soumis"),
                    ("FIX_PROVIDED", "Correctif fourni"),
                    ("FIX_REJECTED", "Correctif jugé insuffisant"),
                    ("FIX_VERIFIED", "Correctif vérifié"),
                    ("DISCLOSURE_SCHEDULED", "Divulgation planifiée"),
                    ("ADVISORY_SUBMITTED", "Advisory soumis en relecture"),
                    ("ADVISORY_PUBLISHED", "Advisory publié"),
                    ("REWARD_PROPOSED", "Prime proposée"),
                    ("REWARD_APPROVED", "Récompense approuvée"),
                    ("REJECTION_PROPOSED", "Rejet proposé"),
                    ("DUPLICATE_MARKED", "Doublon identifié"),
                    ("REJECTED", "Rapport rejeté"),
                    ("RETURNED", "Renvoyé à l'auteur"),
                    ("ESCALATED", "Dossier escaladé"),
                    ("CLOSED", "Case clos"),
                    ("STATUS_CHANGED", "Changement de statut"),
                    ("ASSIGNED", "Assignation"),
                    ("NOTE", "Note"),
                ],
                default="NOTE",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="slaevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ACKNOWLEDGEMENT", "Accusé de réception"),
                    ("TRIAGE", "Recevabilité et analyse"),
                    ("VALIDATION", "Validation de la qualification"),
                    ("VENDOR_RESPONSE", "Réponse de l'organisation"),
                    ("REMEDIATION", "Remédiation"),
                    ("VERIFICATION", "Vérification du correctif"),
                    ("DISCLOSURE", "Divulgation"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="slapolicy",
            name="acknowledgement_hours",
            field=models.PositiveIntegerField(
                default=72, help_text="Étape 1 : accusé de réception."
            ),
        ),
        migrations.AlterField(
            model_name="slapolicy",
            name="remediation_days_high",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name="slapolicy",
            name="remediation_days_medium",
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AlterField(
            model_name="slapolicy",
            name="triage_days",
            field=models.PositiveIntegerField(
                default=5, help_text="Étapes 2 et 3 : recevabilité puis qualification."
            ),
        ),
        migrations.AlterField(
            model_name="slapolicy",
            name="vendor_response_days",
            field=models.PositiveIntegerField(
                default=5, help_text="Étape 6 : plan de remédiation de l'organisation."
            ),
        ),
        migrations.AlterField(
            model_name="slapolicy",
            name="warning_ratio",
            field=models.PositiveSmallIntegerField(
                default=75,
                help_text="Pourcentage du délai à partir duquel la carte passe en orange.",
            ),
        ),
    ]
