# Generated by Django 5.2.17 on 2026-09-30 22:23

from django.db import migrations, models

#: Role du compte -> badge. Toute prise en charge posait "ANALYST", meme
#: pour un agent de triage, un coordinateur ou un compte d'organisation.
BADGES = {
    "TRIAGER": "TRIAGER",
    "NATIONAL_COORDINATOR": "COORDINATOR",
    "DSI_ADMIN": "DSI",
    "ORGANIZATION_MANAGER": "ORGANIZATION",
}


def corriger_badges(apps, schema_editor):
    CaseParticipant = apps.get_model("coordination", "CaseParticipant")
    mal_etiquetes = CaseParticipant.objects.filter(participant_role="ANALYST").exclude(
        user__role="CSIRT_ANALYST"
    )
    for role, badge in BADGES.items():
        mal_etiquetes.filter(user__role=role).update(participant_role=badge)
    mal_etiquetes.update(participant_role="OBSERVER")


class Migration(migrations.Migration):

    dependencies = [
        ("coordination", "0008_workflow_v2_donnees"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseparticipant",
            name="participant_role",
            field=models.CharField(
                choices=[
                    ("REPORTER", "Déclarant"),
                    ("TRIAGER", "Agent de triage"),
                    ("ANALYST", "Analyste CSIRT"),
                    ("COORDINATOR", "Coordinateur"),
                    ("ORGANIZATION", "Organisation affectée"),
                    ("DSI", "DSI"),
                    ("OBSERVER", "Observateur"),
                ],
                default="OBSERVER",
                max_length=16,
            ),
        ),
        migrations.RunPython(corriger_badges, migrations.RunPython.noop),
    ]
