# Generated by Django 5.2.17 on 2026-10-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coordination", "0009_role_participant_agent_de_triage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="casetimelineevent",
            options={
                "ordering": ["occurred_at", "created_at"],
                "verbose_name": "Événement de chronologie",
                "verbose_name_plural": "Chronologie",
            },
        ),
        migrations.AlterModelOptions(
            name="slaevent",
            options={
                "ordering": ["due_at"],
                "verbose_name": "Échéance SLA",
                "verbose_name_plural": "Échéances SLA",
            },
        ),
        migrations.AlterField(
            model_name="slaevent",
            name="state",
            field=models.CharField(
                choices=[
                    ("PENDING", "En cours"),
                    ("APPROACHING", "Échéance proche"),
                    ("MET", "Respecté"),
                    ("BREACHED", "Dépassé"),
                    ("CANCELLED", "Annulé"),
                ],
                db_index=True,
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
