# Generated by Django 5.2.17 on 2026-09-05 21:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('programs', '0001_initial'),
        ('vulnerabilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VulnerabilityReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('product', models.CharField(blank=True, help_text='Produit, service ou application affecte.', max_length=200)),
                ('affected_organization_name', models.CharField(blank=True, help_text="Nom saisi librement si l'organisation n'est pas encore referencee.", max_length=200)),
                ('target_url', models.CharField(blank=True, max_length=500)),
                ('vulnerability_type', models.CharField(choices=[('AUTHENTICATION', 'Authentification'), ('AUTHORIZATION', "Autorisation / controle d'acces"), ('XSS', 'Cross-Site Scripting (XSS)'), ('SQLI', 'Injection SQL'), ('SSRF', 'Server-Side Request Forgery (SSRF)'), ('RCE', 'Execution de code a distance (RCE)'), ('LFI_RFI', 'Inclusion de fichier (LFI/RFI)'), ('IDOR', 'Reference directe non securisee (IDOR)'), ('CSRF', 'Cross-Site Request Forgery (CSRF)'), ('INFO_DISCLOSURE', "Divulgation d'information"), ('MISCONFIGURATION', 'Mauvaise configuration'), ('CRYPTO', 'Probleme cryptographique'), ('BUSINESS_LOGIC', 'Logique metier'), ('API_SECURITY', 'Securite des API'), ('MOBILE', 'Application mobile'), ('CLOUD', 'Cloud'), ('NETWORK', 'Reseau / infrastructure'), ('OTHER', 'Autre')], default='OTHER', max_length=24)),
                ('cvss_vector', models.CharField(blank=True, max_length=120)),
                ('cvss_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('reported_severity', models.CharField(choices=[('CRITICAL', 'Critique'), ('HIGH', 'Elevee'), ('MEDIUM', 'Moyenne'), ('LOW', 'Faible'), ('INFO', 'Informative')], default='MEDIUM', help_text='Severite estimee par le declarant (revue lors du triage).', max_length=16)),
                ('description', models.TextField(help_text='Markdown autorise.')),
                ('steps_to_reproduce', models.TextField(blank=True, help_text='Markdown autorise.')),
                ('impact', models.TextField(blank=True, help_text='Markdown autorise.')),
                ('proof_of_concept', models.TextField(blank=True, help_text='Markdown autorise.')),
                ('recommendations', models.TextField(blank=True, help_text='Markdown autorise.')),
                ('affected_version', models.CharField(blank=True, max_length=120)),
                ('fixed_version', models.CharField(blank=True, max_length=120)),
                ('environment', models.CharField(blank=True, max_length=180)),
                ('external_reference', models.CharField(blank=True, max_length=500)),
                ('reporter_email', models.EmailField(blank=True, help_text='Utilise pour les signalements anonymes.', max_length=254)),
                ('reporter_name', models.CharField(blank=True, max_length=150)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('wants_credit', models.BooleanField(default=True, help_text="Souhaite etre credite dans l'advisory public.")),
                ('requests_cve', models.BooleanField(default=False)),
                ('accepted_policy', models.BooleanField(default=False)),
                ('is_pgp_encrypted', models.BooleanField(default=False)),
                ('pgp_payload', models.TextField(blank=True, help_text="Bloc PGP chiffre. eVDP ne detient aucune cle privee : le dechiffrement est effectue hors ligne par l'equipe destinataire.")),
                ('pgp_signature_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('SUBMITTED', 'Soumis')], default='SUBMITTED', max_length=16)),
                ('source', models.CharField(choices=[('WEB', 'Formulaire web'), ('API', 'API'), ('EMAIL', 'Email'), ('CSAF', 'Import CSAF'), ('INTERNAL', 'Interne')], default='WEB', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submitter_ip_hash', models.CharField(blank=True, help_text="Empreinte de l'IP (anti-abus) - l'IP brute n'est pas conservee.", max_length=64)),
                ('affected_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='organizations.organization')),
                ('cwe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='vulnerabilities.cwe')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='programs.program')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport de vulnerabilite',
                'verbose_name_plural': 'Rapports de vulnerabilite',
                'db_table': 'vulnerability_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='vulnerabili_created_2c8d65_idx'), models.Index(fields=['vulnerability_type'], name='vulnerabili_vulnera_5b46e9_idx')],
            },
        ),
    ]
