# Generated by Django 5.2.17 on 2026-09-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_remove_vulnerabilityreport_pgp_signature_verified"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vulnerabilityreport",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Rapport de vulnérabilité",
                "verbose_name_plural": "Rapports de vulnérabilité",
            },
        ),
        migrations.AlterField(
            model_name="vulnerabilityreport",
            name="affected_organization_name",
            field=models.CharField(
                blank=True,
                help_text="Nom saisi librement si l'organisation n'est pas encore référencée.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityreport",
            name="description",
            field=models.TextField(help_text="Markdown autorisé."),
        ),
        migrations.AlterField(
            model_name="vulnerabilityreport",
            name="impact",
            field=models.TextField(blank=True, help_text="Markdown autorisé."),
        ),
        migrations.AlterField(
            model_name="vulnerabilityreport",
            name="pgp_payload",
            field=models.TextField(
                blank=True,
                help_text="Bloc PGP chiffré. eVDP ne détient aucune clé privée : le déchiffrement est effectué hors ligne par l'équipe destinataire.",
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityreport",
            name="product",
            field=models.CharField(
                blank=True,
                help_text="Produit, service ou application affecté.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityreport",
            name="proof_of_concept",
            field=models.TextField(blank=True, help_text="Markdown autorisé."),
        ),
        migrations.AlterField(
            model_name="vulnerabilityreport",
            name="recommendations",
            field=models.TextField(blank=True, help_text="Markdown autorisé."),
        ),
        migrations.AlterField(
            model_name="vulnerabilityreport",
            name="reported_severity",
            field=models.CharField(
                choices=[
                    ("CRITICAL", "Critique"),
                    ("HIGH", "Élevée"),
                    ("MEDIUM", "Moyenne"),
                    ("LOW", "Faible"),
                    ("INFO", "Informative"),
                ],
                default="MEDIUM",
                help_text="Sévérité estimée par le déclarant (revue lors du triage).",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityreport",
            name="reporter_email",
            field=models.EmailField(
                blank=True, help_text="Utilisé pour les signalements anonymes.", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityreport",
            name="steps_to_reproduce",
            field=models.TextField(blank=True, help_text="Markdown autorisé."),
        ),
        migrations.AlterField(
            model_name="vulnerabilityreport",
            name="submitter_ip_hash",
            field=models.CharField(
                blank=True,
                help_text="Empreinte de l'IP (anti-abus) - l'IP brute n'est pas conservée.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityreport",
            name="vulnerability_type",
            field=models.CharField(
                choices=[
                    ("AUTHENTICATION", "Authentification"),
                    ("AUTHORIZATION", "Autorisation / contrôle d'accès"),
                    ("XSS", "Cross-Site Scripting (XSS)"),
                    ("SQLI", "Injection SQL"),
                    ("SSRF", "Server-Side Request Forgery (SSRF)"),
                    ("RCE", "Exécution de code à distance (RCE)"),
                    ("LFI_RFI", "Inclusion de fichier (LFI/RFI)"),
                    ("IDOR", "Référence directe non sécurisée (IDOR)"),
                    ("CSRF", "Cross-Site Request Forgery (CSRF)"),
                    ("INFO_DISCLOSURE", "Divulgation d'information"),
                    ("MISCONFIGURATION", "Mauvaise configuration"),
                    ("CRYPTO", "Problème cryptographique"),
                    ("BUSINESS_LOGIC", "Logique métier"),
                    ("API_SECURITY", "Sécurité des API"),
                    ("MOBILE", "Application mobile"),
                    ("CLOUD", "Cloud"),
                    ("NETWORK", "Réseau / infrastructure"),
                    ("OTHER", "Autre"),
                ],
                default="OTHER",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="vulnerabilityreport",
            name="wants_credit",
            field=models.BooleanField(
                default=True, help_text="Souhaite être crédité dans l'advisory public."
            ),
        ),
    ]
