# Generated by Django 5.2.17 on 2026-10-01 01:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0004_alter_vulnerabilityreport_cvss_vector"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vulnerabilityreport",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Rapport de vulnérabilité",
                "verbose_name_plural": "Rapports de vulnérabilité",
            },
        ),
    ]
