# Generated by Django 5.2.17 on 2026-09-05 21:19

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bounty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critique'), ('HIGH', 'Elevee'), ('MEDIUM', 'Moyenne'), ('LOW', 'Faible'), ('INFO', 'Informative')], default='MEDIUM', max_length=16)),
                ('proposed_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='XOF', max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Proposee'), ('UNDER_REVIEW', 'En revue'), ('APPROVED', 'Approuvee'), ('REJECTED', 'Rejetee'), ('PAID', 'Payee'), ('CANCELLED', 'Annulee')], db_index=True, default='PENDING', max_length=16)),
                ('justification', models.TextField(blank=True, help_text='Markdown autorise.')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Recompense',
                'verbose_name_plural': 'Recompenses',
                'db_table': 'bounties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BountyPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='XOF', max_length=8)),
                ('method', models.CharField(choices=[('BANK_TRANSFER', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile money'), ('OTHER', 'Autre')], default='BANK_TRANSFER', max_length=24)),
                ('status', models.CharField(choices=[('RECORDED', 'Enregistre'), ('SETTLED', 'Verse'), ('FAILED', 'Echec')], default='RECORDED', max_length=16)),
                ('reference', models.CharField(blank=True, help_text='Reference comptable externe.', max_length=120)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Paiement de recompense',
                'verbose_name_plural': 'Paiements de recompense',
                'db_table': 'bounty_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BountyReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('APPROVE', 'Favorable'), ('REJECT', 'Defavorable'), ('ADJUST', 'Ajustement propose'), ('COMMENT', 'Commentaire')], max_length=16)),
                ('suggested_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Revue de recompense',
                'verbose_name_plural': 'Revues de recompense',
                'db_table': 'bounty_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
