# Generated by Django 5.2.17 on 2026-09-05 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bounty', '0001_initial'),
        ('coordination', '0001_initial'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='case',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bounty', to='coordination.case'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_bounties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bounty',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounties', to='programs.program'),
        ),
        migrations.AddField(
            model_name='bounty',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_bounties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bounty',
            name='researcher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bountypayment',
            name='bounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bounty.bounty'),
        ),
        migrations.AddField(
            model_name='bountypayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bountyreview',
            name='bounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='bounty.bounty'),
        ),
        migrations.AddField(
            model_name='bountyreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounty_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
