# Generated by Django 5.2.17 on 2026-09-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bounty", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bounty",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Récompense",
                "verbose_name_plural": "Récompenses",
            },
        ),
        migrations.AlterModelOptions(
            name="bountypayment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Paiement de récompense",
                "verbose_name_plural": "Paiements de récompense",
            },
        ),
        migrations.AlterModelOptions(
            name="bountyreview",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Revue de récompense",
                "verbose_name_plural": "Revues de récompense",
            },
        ),
        migrations.AlterField(
            model_name="bounty",
            name="justification",
            field=models.TextField(blank=True, help_text="Markdown autorisé."),
        ),
        migrations.AlterField(
            model_name="bounty",
            name="severity",
            field=models.CharField(
                choices=[
                    ("CRITICAL", "Critique"),
                    ("HIGH", "Élevée"),
                    ("MEDIUM", "Moyenne"),
                    ("LOW", "Faible"),
                    ("INFO", "Informative"),
                ],
                default="MEDIUM",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="bounty",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Proposée"),
                    ("UNDER_REVIEW", "En revue"),
                    ("APPROVED", "Approuvée"),
                    ("REJECTED", "Rejetée"),
                    ("PAID", "Payée"),
                    ("CANCELLED", "Annulée"),
                ],
                db_index=True,
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="bountypayment",
            name="reference",
            field=models.CharField(
                blank=True, help_text="Référence comptable externe.", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="bountypayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("RECORDED", "Enregistré"),
                    ("SETTLED", "Versé"),
                    ("FAILED", "Échec"),
                ],
                default="RECORDED",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="bountyreview",
            name="decision",
            field=models.CharField(
                choices=[
                    ("APPROVE", "Favorable"),
                    ("REJECT", "Défavorable"),
                    ("ADJUST", "Ajustement proposé"),
                    ("COMMENT", "Commentaire"),
                ],
                max_length=16,
            ),
        ),
    ]
