# Generated by Django 5.2.17 on 2026-09-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bounty", "0003_alter_bounty_justification_alter_bounty_severity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bountypayment",
            name="payout_snapshot",
            field=models.CharField(
                blank=True,
                help_text="Resume masque du moyen de paiement principal declare par le chercheur au moment du versement (voir apps.researchers.PayoutMethod). Copie a titre indicatif, jamais une reference forte : le wallet peut changer ou etre desactive apres coup sans alterer cet historique.",
                max_length=255,
            ),
        ),
    ]
