# Generated by Django 5.2.17 on 2026-09-23 16:51

import apps.bounty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bounty", "0004_bountypayment_payout_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="bountypayment",
            name="failure_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="bountypayment",
            name="proof_content_type",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="bountypayment",
            name="proof_file",
            field=models.FileField(
                blank=True,
                max_length=300,
                upload_to=apps.bounty.models.payment_proof_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="bountypayment",
            name="proof_original_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="bountypayment",
            name="proof_sha256",
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name="bountypayment",
            name="proof_size",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="bountypayment",
            name="proof_storage_name",
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name="bountypayment",
            name="proof_uploaded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
