# Generated by Django 5.2.17 on 2026-09-24 16:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bounty", "0004_bountypayment_payout_snapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CREDIT", "Crédit (prime approuvée)"),
                            ("ADJUSTMENT", "Ajustement"),
                            ("PAYOUT", "Versement hors plateforme"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Montant signé : positif au crédit, négatif au débit.",
                        max_digits=12,
                    ),
                ),
                ("currency", models.CharField(default="XOF", max_length=8)),
                ("label", models.CharField(blank=True, max_length=255)),
                (
                    "bounty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet_entries",
                        to="bounty.bounty",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_entries_recorded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "researcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Écriture de Wallet",
                "verbose_name_plural": "Grand livre du Wallet",
                "db_table": "wallet_entries",
                "ordering": ["-created_at"],
            },
        ),
    ]
