# Generated by Django 5.2.17 on 2026-09-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bounty", "0005_bountypayment_failure_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bounty",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Proposée"),
                    ("UNDER_REVIEW", "En revue"),
                    ("APPROVED", "Approuvée"),
                    ("REJECTED", "Rejetée"),
                    ("PAYMENT_PENDING", "Versement en attente de confirmation"),
                    ("PAID", "Payée"),
                    ("CANCELLED", "Annulée"),
                ],
                db_index=True,
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
