# Generated by Django 5.2.17 on 2026-10-01 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bounty", "0007_walletentry"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bounty",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Récompense",
                "verbose_name_plural": "Récompenses",
            },
        ),
        migrations.AlterModelOptions(
            name="bountypayment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Paiement de récompense",
                "verbose_name_plural": "Paiements de récompense",
            },
        ),
        migrations.AlterModelOptions(
            name="bountyreview",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Revue de récompense",
                "verbose_name_plural": "Revues de récompense",
            },
        ),
        migrations.AlterField(
            model_name="bountypayment",
            name="payout_snapshot",
            field=models.CharField(
                blank=True,
                help_text="Résumé masqué du moyen de paiement principal déclaré par le chercheur au moment du versement (voir apps.researchers.PayoutMethod). Copie à titre indicatif, jamais une référence forte : le wallet peut changer ou être désactivé après coup sans altérer cet historique.",
                max_length=255,
            ),
        ),
    ]
