# Generated by Django 5.2.17 on 2026-09-05 21:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('acronym', models.CharField(blank=True, max_length=32)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('organization_type', models.CharField(choices=[('PUBLIC_ADMIN', 'Administration publique'), ('MINISTRY', 'Ministere'), ('LOCAL_AUTHORITY', 'Collectivite territoriale'), ('PUBLIC_INSTITUTION', 'Etablissement public'), ('PUBLIC_COMPANY', 'Entreprise publique'), ('PRIVATE_COMPANY', 'Entreprise privee'), ('OPERATOR', "Operateur d'importance vitale"), ('UNIVERSITY', 'Universite / recherche'), ('OTHER', 'Autre')], default='OTHER', max_length=32)),
                ('sector', models.CharField(choices=[('GOVERNMENT', 'Gouvernement'), ('DEFENSE', 'Defense et securite'), ('HEALTH', 'Sante'), ('EDUCATION', 'Education'), ('FINANCE', 'Finance et banque'), ('TELECOM', 'Telecommunications'), ('ENERGY', 'Energie'), ('WATER', 'Eau et assainissement'), ('TRANSPORT', 'Transport'), ('JUSTICE', 'Justice'), ('AGRICULTURE', 'Agriculture'), ('INDUSTRY', 'Industrie'), ('OTHER', 'Autre')], db_index=True, default='OTHER', max_length=32)),
                ('domain', models.CharField(blank=True, help_text='Domaine principal, ex. sante.gov.bf', max_length=180)),
                ('official_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'En attente de validation'), ('SUSPENDED', 'Suspendue'), ('ARCHIVED', 'Archivee')], db_index=True, default='ACTIVE', max_length=16)),
                ('dsi_name', models.CharField(blank=True, max_length=150, verbose_name='Responsable DSI')),
                ('dsi_email', models.EmailField(blank=True, max_length=254)),
                ('manager_name', models.CharField(blank=True, max_length=150)),
                ('manager_email', models.EmailField(blank=True, max_length=254)),
                ('pgp_public_key', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('accepts_vdp', models.BooleanField(default=True, help_text='Accepte de recevoir des signalements via eVDP.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SecurityContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('pgp_public_key', models.TextField(blank=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_contacts', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Contact securite',
                'verbose_name_plural': 'Contacts securite',
                'db_table': 'organization_security_contacts',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_role', models.CharField(choices=[('MANAGER', 'Responsable'), ('DSI', 'DSI'), ('SECURITY_CONTACT', 'Contact securite'), ('ANALYST', 'Analyste'), ('OBSERVER', 'Observateur')], default='OBSERVER', max_length=24)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_org_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Membre d'organisation",
                'verbose_name_plural': "Membres d'organisation",
                'db_table': 'organization_members',
                'ordering': ['organization__name', 'user__email'],
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
