# Generated by Django 5.2.17 on 2026-09-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='pgp_public_key',
            field=models.TextField(blank=True, help_text="Contact direct de l'organisation, hors plateforme eVDP. Le formulaire de signalement eVDP propose toujours la cle nationale, jamais celle-ci : chaque dossier doit rester lisible par le CSIRT national pour le triage."),
        ),
        migrations.AlterField(
            model_name='securitycontact',
            name='pgp_public_key',
            field=models.TextField(blank=True, help_text='Contact direct de ce point de contact, hors plateforme eVDP. Le formulaire de signalement eVDP propose toujours la cle nationale, jamais celle-ci : chaque dossier doit rester lisible par le CSIRT national pour le triage.'),
        ),
    ]
