# Generated by Django 5.2.17 on 2026-10-01 01:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_alter_organization_organization_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="securitycontact",
            options={
                "ordering": ["-is_primary", "name"],
                "verbose_name": "Contact sécurité",
                "verbose_name_plural": "Contacts sécurité",
            },
        ),
    ]
