# Generated by Django 5.2.17 on 2026-09-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_clarify_pgp_key_help_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="securitycontact",
            options={
                "ordering": ["-is_primary", "name"],
                "verbose_name": "Contact sécurité",
                "verbose_name_plural": "Contacts sécurité",
            },
        ),
        migrations.AlterField(
            model_name="organization",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("PUBLIC_ADMIN", "Administration publique"),
                    ("MINISTRY", "Ministère"),
                    ("LOCAL_AUTHORITY", "Collectivité territoriale"),
                    ("PUBLIC_INSTITUTION", "Établissement public"),
                    ("PUBLIC_COMPANY", "Entreprise publique"),
                    ("PRIVATE_COMPANY", "Entreprise privée"),
                    ("OPERATOR", "Opérateur d'importance vitale"),
                    ("UNIVERSITY", "Université / recherche"),
                    ("OTHER", "Autre"),
                ],
                default="OTHER",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="pgp_public_key",
            field=models.TextField(
                blank=True,
                help_text="Contact direct de l'organisation, hors plateforme eVDP. Le formulaire de signalement eVDP propose toujours la clé nationale, jamais celle-ci : chaque dossier doit rester lisible par le CSIRT national pour le triage.",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="sector",
            field=models.CharField(
                choices=[
                    ("GOVERNMENT", "Gouvernement"),
                    ("DEFENSE", "Défense et sécurité"),
                    ("HEALTH", "Santé"),
                    ("EDUCATION", "Éducation"),
                    ("FINANCE", "Finance et banque"),
                    ("TELECOM", "Télécommunications"),
                    ("ENERGY", "Énergie"),
                    ("WATER", "Eau et assainissement"),
                    ("TRANSPORT", "Transport"),
                    ("JUSTICE", "Justice"),
                    ("AGRICULTURE", "Agriculture"),
                    ("INDUSTRY", "Industrie"),
                    ("OTHER", "Autre"),
                ],
                db_index=True,
                default="OTHER",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("PENDING", "En attente de validation"),
                    ("SUSPENDED", "Suspendue"),
                    ("ARCHIVED", "Archivée"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmember",
            name="membership_role",
            field=models.CharField(
                choices=[
                    ("MANAGER", "Responsable"),
                    ("DSI", "DSI"),
                    ("SECURITY_CONTACT", "Contact sécurité"),
                    ("ANALYST", "Analyste"),
                    ("OBSERVER", "Observateur"),
                ],
                default="OBSERVER",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="securitycontact",
            name="pgp_public_key",
            field=models.TextField(
                blank=True,
                help_text="Contact direct de ce point de contact, hors plateforme eVDP. Le formulaire de signalement eVDP propose toujours la clé nationale, jamais celle-ci : chaque dossier doit rester lisible par le CSIRT national pour le triage.",
            ),
        ),
    ]
