# Generated by Django 5.2.17 on 2026-09-05 21:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coordination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('REPORT_RECEIVED', 'Nouveau rapport'), ('ACKNOWLEDGEMENT', 'Accuse de reception'), ('INFORMATION_REQUESTED', "Demande d'informations"), ('STATUS_CHANGED', 'Changement de statut'), ('NEW_MESSAGE', 'Nouveau message'), ('NEW_ATTACHMENT', 'Nouvelle piece jointe'), ('CASE_ASSIGNED', 'Case assigne'), ('VALIDATED', 'Rapport valide'), ('REJECTED', 'Rapport rejete'), ('DUPLICATE', 'Rapport en doublon'), ('SLA_APPROACHING', 'Echeance SLA proche'), ('SLA_BREACHED', 'SLA depasse'), ('DISCLOSURE_UPCOMING', 'Divulgation imminente'), ('ADVISORY_PUBLISHED', 'Advisory publie'), ('BOUNTY_PROPOSED', 'Recompense proposee'), ('BOUNTY_APPROVED', 'Recompense approuvee'), ('BOUNTY_REJECTED', 'Recompense rejetee'), ('BOUNTY_PAID', 'Recompense payee'), ('ACCOUNT', 'Compte')], max_length=48, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Variables disponibles : {case_id}, {title}, {status}, {link}.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Modele d'email",
                'verbose_name_plural': "Modeles d'email",
                'db_table': 'email_templates',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('REPORT_RECEIVED', 'Nouveau rapport'), ('ACKNOWLEDGEMENT', 'Accuse de reception'), ('INFORMATION_REQUESTED', "Demande d'informations"), ('STATUS_CHANGED', 'Changement de statut'), ('NEW_MESSAGE', 'Nouveau message'), ('NEW_ATTACHMENT', 'Nouvelle piece jointe'), ('CASE_ASSIGNED', 'Case assigne'), ('VALIDATED', 'Rapport valide'), ('REJECTED', 'Rapport rejete'), ('DUPLICATE', 'Rapport en doublon'), ('SLA_APPROACHING', 'Echeance SLA proche'), ('SLA_BREACHED', 'SLA depasse'), ('DISCLOSURE_UPCOMING', 'Divulgation imminente'), ('ADVISORY_PUBLISHED', 'Advisory publie'), ('BOUNTY_PROPOSED', 'Recompense proposee'), ('BOUNTY_APPROVED', 'Recompense approuvee'), ('BOUNTY_REJECTED', 'Recompense rejetee'), ('BOUNTY_PAID', 'Recompense payee'), ('ACCOUNT', 'Compte')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, help_text='Message court et non sensible.', max_length=400)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='coordination.case')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_8dcb32_idx')],
            },
        ),
    ]
