# Generated by Django 5.2.17 on 2026-09-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="code",
            field=models.CharField(
                choices=[
                    ("REPORT_RECEIVED", "Nouveau rapport"),
                    ("ACKNOWLEDGEMENT", "Accusé de réception"),
                    ("INFORMATION_REQUESTED", "Demande d'informations"),
                    ("STATUS_CHANGED", "Changement de statut"),
                    ("NEW_MESSAGE", "Nouveau message"),
                    ("NEW_ATTACHMENT", "Nouvelle pièce jointe"),
                    ("CASE_ASSIGNED", "Case assigné"),
                    ("VALIDATED", "Rapport validé"),
                    ("REJECTED", "Rapport rejeté"),
                    ("DUPLICATE", "Rapport en doublon"),
                    ("SLA_APPROACHING", "Échéance SLA proche"),
                    ("SLA_BREACHED", "SLA dépassé"),
                    ("DISCLOSURE_UPCOMING", "Divulgation imminente"),
                    ("ADVISORY_PUBLISHED", "Advisory publié"),
                    ("BOUNTY_PROPOSED", "Récompense proposée"),
                    ("BOUNTY_APPROVED", "Récompense approuvée"),
                    ("BOUNTY_REJECTED", "Récompense rejetée"),
                    ("BOUNTY_PAID", "Récompense payée"),
                    ("ACCOUNT", "Compte"),
                ],
                max_length=48,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("REPORT_RECEIVED", "Nouveau rapport"),
                    ("ACKNOWLEDGEMENT", "Accusé de réception"),
                    ("INFORMATION_REQUESTED", "Demande d'informations"),
                    ("STATUS_CHANGED", "Changement de statut"),
                    ("NEW_MESSAGE", "Nouveau message"),
                    ("NEW_ATTACHMENT", "Nouvelle pièce jointe"),
                    ("CASE_ASSIGNED", "Case assigné"),
                    ("VALIDATED", "Rapport validé"),
                    ("REJECTED", "Rapport rejeté"),
                    ("DUPLICATE", "Rapport en doublon"),
                    ("SLA_APPROACHING", "Échéance SLA proche"),
                    ("SLA_BREACHED", "SLA dépassé"),
                    ("DISCLOSURE_UPCOMING", "Divulgation imminente"),
                    ("ADVISORY_PUBLISHED", "Advisory publié"),
                    ("BOUNTY_PROPOSED", "Récompense proposée"),
                    ("BOUNTY_APPROVED", "Récompense approuvée"),
                    ("BOUNTY_REJECTED", "Récompense rejetée"),
                    ("BOUNTY_PAID", "Récompense payée"),
                    ("ACCOUNT", "Compte"),
                ],
                max_length=32,
            ),
        ),
    ]
