# Generated by Django 5.2.17 on 2026-09-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="code",
            field=models.CharField(
                choices=[
                    ("REPORT_RECEIVED", "Nouveau rapport"),
                    ("ACKNOWLEDGEMENT", "Accuse de reception"),
                    ("INFORMATION_REQUESTED", "Demande d'informations"),
                    ("STATUS_CHANGED", "Changement de statut"),
                    ("NEW_MESSAGE", "Nouveau message"),
                    ("NEW_ATTACHMENT", "Nouvelle piece jointe"),
                    ("CASE_ASSIGNED", "Case assigne"),
                    ("VALIDATED", "Rapport valide"),
                    ("REJECTED", "Rapport rejete"),
                    ("DUPLICATE", "Rapport en doublon"),
                    ("SLA_APPROACHING", "Echeance SLA proche"),
                    ("SLA_BREACHED", "SLA depasse"),
                    ("DISCLOSURE_UPCOMING", "Divulgation imminente"),
                    ("ADVISORY_PUBLISHED", "Advisory publie"),
                    ("BOUNTY_PROPOSED", "Recompense proposee"),
                    ("BOUNTY_APPROVED", "Recompense approuvee"),
                    ("BOUNTY_REJECTED", "Recompense rejetee"),
                    ("BOUNTY_PAID", "Recompense payee"),
                    ("ACCOUNT", "Compte"),
                    ("TRACKING_LINK", "Lien de suivi (declarant sans compte)"),
                ],
                max_length=48,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("REPORT_RECEIVED", "Nouveau rapport"),
                    ("ACKNOWLEDGEMENT", "Accuse de reception"),
                    ("INFORMATION_REQUESTED", "Demande d'informations"),
                    ("STATUS_CHANGED", "Changement de statut"),
                    ("NEW_MESSAGE", "Nouveau message"),
                    ("NEW_ATTACHMENT", "Nouvelle piece jointe"),
                    ("CASE_ASSIGNED", "Case assigne"),
                    ("VALIDATED", "Rapport valide"),
                    ("REJECTED", "Rapport rejete"),
                    ("DUPLICATE", "Rapport en doublon"),
                    ("SLA_APPROACHING", "Echeance SLA proche"),
                    ("SLA_BREACHED", "SLA depasse"),
                    ("DISCLOSURE_UPCOMING", "Divulgation imminente"),
                    ("ADVISORY_PUBLISHED", "Advisory publie"),
                    ("BOUNTY_PROPOSED", "Recompense proposee"),
                    ("BOUNTY_APPROVED", "Recompense approuvee"),
                    ("BOUNTY_REJECTED", "Recompense rejetee"),
                    ("BOUNTY_PAID", "Recompense payee"),
                    ("ACCOUNT", "Compte"),
                    ("TRACKING_LINK", "Lien de suivi (declarant sans compte)"),
                ],
                max_length=32,
            ),
        ),
    ]
