# Generated by Django 5.2.17 on 2026-09-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_emailtemplate_code_alter_notification_kind"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailtemplate",
            options={
                "ordering": ["code"],
                "verbose_name": "Modèle d'email",
                "verbose_name_plural": "Modèles d'email",
            },
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="code",
            field=models.CharField(
                choices=[
                    ("REPORT_RECEIVED", "Nouveau rapport"),
                    ("ACKNOWLEDGEMENT", "Accusé de réception"),
                    ("INFORMATION_REQUESTED", "Demande d'informations"),
                    ("STATUS_CHANGED", "Changement de statut"),
                    ("NEW_MESSAGE", "Nouveau message"),
                    ("NEW_ATTACHMENT", "Nouvelle pièce jointe"),
                    ("CASE_ASSIGNED", "Case assigné"),
                    ("VALIDATED", "Rapport validé"),
                    ("REJECTED", "Rapport rejeté"),
                    ("DUPLICATE", "Rapport en doublon"),
                    ("SLA_APPROACHING", "Échéance SLA proche"),
                    ("SLA_BREACHED", "SLA dépassé"),
                    ("DISCLOSURE_UPCOMING", "Divulgation imminente"),
                    ("ADVISORY_PUBLISHED", "Advisory publié"),
                    ("BOUNTY_PROPOSED", "Récompense proposée"),
                    ("BOUNTY_APPROVED", "Récompense approuvée"),
                    ("BOUNTY_REJECTED", "Récompense rejetée"),
                    ("BOUNTY_PAID", "Récompense payée"),
                    ("ACCOUNT", "Compte"),
                    ("TRACKING_LINK", "Lien de suivi (déclarant sans compte)"),
                ],
                max_length=48,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("REPORT_RECEIVED", "Nouveau rapport"),
                    ("ACKNOWLEDGEMENT", "Accusé de réception"),
                    ("INFORMATION_REQUESTED", "Demande d'informations"),
                    ("STATUS_CHANGED", "Changement de statut"),
                    ("NEW_MESSAGE", "Nouveau message"),
                    ("NEW_ATTACHMENT", "Nouvelle pièce jointe"),
                    ("CASE_ASSIGNED", "Case assigné"),
                    ("VALIDATED", "Rapport validé"),
                    ("REJECTED", "Rapport rejeté"),
                    ("DUPLICATE", "Rapport en doublon"),
                    ("SLA_APPROACHING", "Échéance SLA proche"),
                    ("SLA_BREACHED", "SLA dépassé"),
                    ("DISCLOSURE_UPCOMING", "Divulgation imminente"),
                    ("ADVISORY_PUBLISHED", "Advisory publié"),
                    ("BOUNTY_PROPOSED", "Récompense proposée"),
                    ("BOUNTY_APPROVED", "Récompense approuvée"),
                    ("BOUNTY_REJECTED", "Récompense rejetée"),
                    ("BOUNTY_PAID", "Récompense payée"),
                    ("ACCOUNT", "Compte"),
                    ("TRACKING_LINK", "Lien de suivi (déclarant sans compte)"),
                ],
                max_length=32,
            ),
        ),
    ]
