# Generated by Django 5.2.17 on 2026-10-01 01:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_alter_emailtemplate_code_alter_notification_kind"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailtemplate",
            options={
                "ordering": ["code"],
                "verbose_name": "Modèle d'email",
                "verbose_name_plural": "Modèles d'email",
            },
        ),
    ]
